### ISSUE TITLE
charm build fails with a large stacktrace when git is not present on the system

### ISSUE THREAD

**Issue by chuckbutler** [juju/charm-tools#102]
when executing `charm build` in a fresh environment without installing git, the process fails with a long stack trace referring to 'file not found' - not indicating that user needs to install git. This seems to be a non issue on packaged versions of charm-tools, however when installing from pip, it wont implicitly pull in git.

**Comment by marcoceppi** [comment]
Better error handling is needed. We had a similar problem on osx until we added git as a dependency in the packaging.
