### ISSUE TITLE
series in metadata deprecates need to put charms in /series/ directory

### ISSUE THREAD

**Issue by marcoceppi** [juju/charm-tools#115]
We should just build them into `$JUJU_REPOSITORY/<charm>` now, or somewhere more generic

**Comment by tvansteenburgh** [comment]
Perhaps we do this if the charm does indeed declare its series in metadata, but if not, continue to build into a series dir?

**Comment by marcoceppi** [comment]
Sounds smart, as long as we continue to tell the use what's going on.
There's also a potential for collision if the charm is called $LAYER_PATH
or INTERFACE_PATH basename. However, I doubt that will be an issue.

**Comment by mitechie** [comment]
What about using this to help users pick a default series? How disruptive would it be to toss a warning/error at the user here?

**Comment by stub42** [comment]
Charms may require no default series to support Juju 1.x, so I'd balk at a warning or error.

**Comment by marcoceppi** [comment]
Whenever there is a `series` key in output, the directory should just be `builds`, otherwise the current series path should continue.
