### ISSUE TITLE
Support layer- and interface- prefix for local layers

### ISSUE THREAD

**Issue by johnsca** [juju/charm-tools#116]
The convention that has come up for repo names for base, interface, and charm layers is to prefix them with ["layer-"](https://github.com/juju-solutions?query=layer-) and ["interface-"](https://github.com/juju-solutions?query=interface-).  When those repos are cloned for local development, you have to be careful to rename the directory to remove the prefix.  It would be nice if `charm build` would handle the prefix automatically.

**Comment by tvansteenburgh** [comment]
There are two ways to do this. Either rename the dir when cloning (to match the layer name), or be aware of the (possible) prefixes when searching the path. Which is preferred? Note that `charm pull-source` does a rename - when you pull-source on a layer or interface, the name of the destination directory will match the name of the layer or interface, not the repo from which it was cloned.

**Comment by tvansteenburgh** [comment]
On second thought maybe we should do both?

**Comment by johnsca** [comment]
If the repo prefixes are standardized, it would be nice to support them for the case when someone just does a `git clone`, but I'm also ok with closing this in favor of recommending always using `charm-pull-source`.

**Comment by tvansteenburgh** [comment]
`charm pull-source` will be the ideal way to get stuff, but I'll throw in support for the `layer-` and `interface-` prefixes anyway since it's such a minor change.
