### ISSUE TITLE
.pypi libraries' script / bin tools are not installed in deployed charm

### ISSUE THREAD

**Issue by johnsca** [juju/charm-tools#13]
Original issue: https://github.com/juju-solutions/charms.reactive/issues/5

Any library installed via a .pypi file in a layer that installs a script or binary CLI tool will fail due to the location that pip tries to install the tool to.  I think this can be fixed simply by having a `bin` directory in the base layer and having that added to the path for all hooks, but I'm not certain.

**Comment by johnsca** [comment]
Can't be fixed in the base layer, as the scripts / bin tools get dropped into a randomly create temp directory by pip during the install (i.e., the `--target` option doesn't work for scripts), and pip doesn't have an analogue to easy_install's `--script-dir`.

After some experimentation, the following gets both the libraries and bin tools under the target dir, as well as processing all the dependencies as it does currently:

    PYTHONUSERBASE=$target pip install --user --ignore-installed $spec

However, this ends up with more nesting in the target dir (`$target/bin`, and `$target/lib/pythonn2.7/site-packages/*`) which will have to be handled.

**Comment by bcsaller** [comment]
Thanks for taking a look at this, I am cutting a branch with the final naming and will make these changes there as well.

**Comment by battlemidget** [comment]
I ran into this issue when attempting to use `lib/pep8.pypi`

**Comment by marcoceppi** [comment]
Fixed with #21
