### ISSUE TITLE
charm proof needs min-juju-version support

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charm-tools#141]
Please add min-juju-version support to charm proof in preparation for the feature landing.  This will allow us to add the metadata to development versions of charms and pass proof.  TIA

**Comment by marcoceppi** [comment]
validation should be any version number that is `X.Y` or `X.Y.Z` where `X` >= 2

**Comment by tvansteenburgh** [comment]
Note that versions such as "2.0.1-beta3" should also be acceptable.

**Comment by marcoceppi** [comment]
should they?

**Comment by tvansteenburgh** [comment]
https://lists.ubuntu.com/archives/juju/2016-March/006850.html

**Comment by natefinch** [comment]
Yes, juju-min-version is parsed using our standard version parsing library, so supports stuff like build tags of beta3, which get compared lexicographically.  The full code is here for parsing: https://github.com/juju/version/blob/master/version.go#L150 and here for comparison: https://github.com/juju/version/blob/master/version.go#L193

That code should be pretty trivial to convert to python, if needed.

**Comment by marcoceppi** [comment]
bleh, okay so

## Valid
- 2.0.1
- 2.1
- 2.10.2-beta1
- 2.10-beta10

## Invalid
- 1.26.0
- 2-beta6
- 0.6.10
- 1.25

Does this seem correct?

**Comment by mbruzek** [comment]
Reading the code link that @natefinch provided @marcoceppi it appears your 3rd case is not valid.

2.10.beta1.2 appears to be the format the code is looking for.

Correct me if I am wrong on that read.

**Comment by marcoceppi** [comment]
It seems we just need this:

`^(\d{1,9})\.(\d{1,9})(\.|-(\w+))(\d{1,9})(\.\d{1,9})?$`

From [version.go#L104](https://github.com/juju/version/blob/master/version.go#L104)
