### ISSUE TITLE
charm proof needs to support extra-bindings

### ISSUE THREAD

**Issue by javacruft** [juju/charm-tools#142]
New feature for juju 2.0; top level metadata entry:

```
extra-bindings:
  a:
  b:
  c:
```

**Comment by marcoceppi** [comment]
Example of implementation: https://github.com/javacruft/charm-neutron-api/blob/665c34bca503edf80c0a5c108b2cf335ec48bcb1/metadata.yaml#L17

**Comment by tvansteenburgh** [comment]
So if present, just assert that it's a dictionary?

**Comment by marcoceppi** [comment]
I suppose so. I don't see anything else that's supposed to go in that dictionary
