### ISSUE TITLE
Remove charmworldlib from charm-tools

### ISSUE THREAD

**Issue by marcoceppi** [juju/charm-tools#144]
replace with libcharmstore

**Comment by tvansteenburgh** [comment]
@marcoceppi Should we remove the "remote proof a bundle" feature? I assume so since the charmstore api doesn't support it?

**Comment by marcoceppi** [comment]
The one from jujubundlelib? That should still work in v4 and 5

**Comment by tvansteenburgh** [comment]
No, the one in charm-tools that calls out to here: http://bazaar.launchpad.net/~charmers/charmworldlib/0.4/view/head:/charmworldlib/bundle.py#L24

**Comment by marcoceppi** [comment]
We need to add that to libcharmstore then please
