### ISSUE TITLE
support a "--no-local-layers" option

### ISSUE THREAD

**Issue by kwmonroe** [juju/charm-tools#149]
On more that one occasion, I have modified a local interface and/or runtime layer, run 'charm build' on something else, and had my local layer in the charm artifact.  It's true I don't read the 'charm build' output as well as I should (at least when it's all green).

I would like an option for 'charm build' that *only* uses interfaces.juju.solutions to pick up included layers.

**Comment by marcoceppi** [comment]
I don't feel like this is really the right way to solve this. It honestly sounds like you're just not using LAYER_PATH to it's full extent.

**Comment by tvansteenburgh** [comment]
You could almost achieve this same thing with:

    LAYER_PATH= INTERFACE_PATH= charm build

But not quite, b/c JUJU_REPOSITORY is also used as a search location for local layers, and if that's not set, it falls back to searching the cwd. You could set JUJU_REPOSITORY=/dev/null also to make sure you get no local layers, but now we're just getting weird, and potentially stomping on other parts of the program (such as those that determine where to put the built charm).

In the end, maybe the flag is the best way? I dunno, just my $.02

**Comment by johnsca** [comment]
I work around this by using a "virtualenv-like" workflow where I (have helpers that) create a separate set of (clean) directories to serve as the `LAYER_PATH` ,`INTERFACE_PATH`, and `JUJU_REPOSITORY` but that is still tedious for doing a quick re-build of a charm layer for publishing while ensuring that I don't accidentally pull in WIP changes from my myriad of local layers & interfaces.
