### ISSUE TITLE
charm-tools as of 2.0 pulls in x11

### ISSUE THREAD

**Issue by chuckbutler** [juju/charm-tools#154]
This appears to be due to mercurial pulling in tcl, which pulls in x11. 

These recommends directives are bloating our tooling and imagery with x11-common, tcl, and other depends we don't need. Can we change these to --no-recommends, or perhaps consider another method to reduce the overall incoming packages?

**Comment by marcoceppi** [comment]
This was fixed by making hg a suggestion
