### ISSUE TITLE
Unable to Install on ppc64el Xenial

### ISSUE THREAD

**Issue by arosales** [juju/charm-tools#158]
ubuntu@stilson-02:~/charms$sudo add-apt-repository ppa:juju/devel

ubuntu@stilson-02:~/charms$sudo apt-get update && sudo apt-get install juju2

ubuntu@stilson-02:~/charms$ sudo apt-get install charm-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 charm-tools : Depends: python-libcharmstore (>= 0.0.3) but it is not installable
               Depends: python-pathspec but it is not installable
               Depends: python-otherstuf but it is not installable
               Depends: python-path.py but it is not installable
               Depends: python-jujubundlelib but it is not installable
               Depends: charm (>= 2:2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

ubuntu@stilson-02:~/charms$

**Comment by marcoceppi** [comment]
This is a known issue, and is mainly due to charm not building properly on ppc64el for wily or xenial (works fine in trusty)
