### ISSUE TITLE
charm-tools has unmet dependencies

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#179]
I am on the development branch of Xenial (16.04). I did my normal `apt-get update` and `apt-get upgrade`. Today I saw that charm-tools was available so I ran `apt-get dist-upgrade` to get it. The charm-tools package had some unmet dependencies.

```
mbruzek@warhorse:~$ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 charm-tools : Depends: python-path but it is not installed
E: Unmet dependencies. Try using -f.
```

**Comment by marcoceppi** [comment]
This was due to amulet requiring python-path.py which conflicts with python-path. Amulet and python-path have been updated to address this
