### ISSUE TITLE
Custom layer tatics are loaded with a global scope

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#184]
While writing our custom WheelhouseTactic for layer-docker we found that tactics do not need to import templfile, or path.py libraries because the global scope of charmtools.utils.load_class() is passed to the execfile method. A better way to do this is to use importlib.load_module() or something else to load these custom tactics.

See https://github.com/juju-solutions/layer-docker/pull/43 for more details.

```
# The references to process, path, and tempfile are implicit below because
# they come from the global scope of charmtools.utils which gets passed in during 
# charmtools.utils.load_class
```

**Comment by mbruzek** [comment]
We should look at using import_module instead of execfile in tatics.py:
https://docs.python.org/2/library/importlib.html#importlib.import_module

**Comment by bcsaller** [comment]
There is a patch doing this at
https://github.com/juju/charm-tools/tree/fix_tactic_loader I am waiting on
testing before making the PR
