### ISSUE TITLE
'charm login' gets an oauth token, fails to use it

### ISSUE THREAD

**Issue by stub42** [juju/charm-tools#188]
charm login successfully creates an oauth token (I can see it in the SSO web interface), but seems incapable of actually using it.

$ charm login
Login to Ubuntu SSO
Press return to select a default value.
E-Mail: stuart@stuartbishop.net
Password: 
Two-factor auth (Enter for none): 123456
ERROR login failed: invalid OAuth credentials

**Comment by johnsca** [comment]
Most of the `charm` commands, including login, are actually in https://github.com/juju/charmstore-client and this particular issue is possibly addressed in https://github.com/juju/charmstore-client/issues/44

**Comment by johnsca** [comment]
Might also be related to https://github.com/juju/charmstore-client/issues/41

**Comment by stub42** [comment]
It looks like a different bug, as the work around does not help. I've moved this to juju/charmstore-client#51
