### ISSUE TITLE
`charm build` should be connecting to interfaces.juju.solutions with TLS

### ISSUE THREAD

**Issue by cmars** [juju/charm-tools#206]
The connection to interfaces.juju.solutions should be TLS-secured, since it is used to redirect `charm build` to authoritative Git repositories for each layer/interface registered. An attacker could replace legitimate layer and interface repos with their own, and inject malicious code into a charm at build time.

I recommend [Let's Encrypt](https://letsencrypt.org/getting-started/) if you're managing this site yourselves. It can be easily set up in minutes.

## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [x] Provide versions of tools used
 - [x] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
$ charm version
charm 2.1.1-0ubuntu1
charm-tools 2.1.2
```

I am using: (Your operating system)

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
```

### I expect/expected the following

Connections to `https://interfaces.juju.solutions`. Automatic redirect from `http://interfaces.juju.solutions` to `https://interfaces.juju.solutions` when loading the page in a browser. https:// in URLs when grepping the charmtools sources.

### What I got

No redirect. Insecure connection to `http://interfaces.juju.solutions`.

**Comment by marcoceppi** [comment]
This is on our roadmap, we need to update the service running since it's a docker container atm.

**Comment by chuckbutler** [comment]
Duplicated by #32

**Comment by marcoceppi** [comment]
Thanks, knew it was somewhere, couldn't find it.
