### ISSUE TITLE
According to the release notes, we have improper parsing on min-juju-version

### ISSUE THREAD

**Issue by chuckbutler** [juju/charm-tools#207]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
ubuntu@devbox:~/xenial/etcd$ charm version
charm error
charm-tools 2.1.2
```

I am using: ubuntu 14.04

## Issue/Feature

charm proof

### I expect/expected the following

Clean output when using the following in metadata.yaml:

```
min-juju-version: 2.0.0-beta6
```

### What I got

ubuntu@devbox:~/xenial/etcd$ charm proof
E: min-juju-version: invalid format, try X.Y.Z

### Related snippet from the docs:

Charms can declare minimum Juju version

There is a new (optional) top level field in the metadata.yaml file called min-juju-version. If supplied, this value specifies the minimum version of a Juju server with which the charm is compatible. When a user attempts to deploy a charm (whether from the charmstore or from local) that has min-juju-version specified, if the targeted model's Juju version is lower than that specified, then the user will be shown an error noting that the charm requires a newer version of Juju (and told what version they need). The format for min-juju-version is a string that follows the same scheme as our release versions, so you can be as specific as you like. For example, min-juju-version: "2.0.1-beta3" will deploy on 2.0.1 (release), but will not deploy on 2.0.1-alpha1 (since alpha1 is older than beta3).

Note that, at this time, Juju 1.25.x does not recognize this field, so charms using this field will, unfortunately, not be accepted by 1.25 environments.

**Comment by chuckbutler** [comment]
It does appear however that 2.0-beta6 cleaned up the output of charm proof.

**Comment by tvansteenburgh** [comment]
The regex used in charm-proof is the same one used by juju itself (here https://github.com/juju/version/blob/master/version.go#L104). In other words, the examples in the docs are invalid, according to the code.

**Comment by chuckbutler** [comment]
Not a problem with charm-tools.
