### ISSUE TITLE
Charm tools whoami doesn't find my group

### ISSUE THREAD

**Issue by buggtb** [juju/charm-tools#211]
Alright then big Oauth issues it seems:

bugg@tomsdevbox:~/charms/trusty/joshua-full$ charm version
charm 2.1.1-0ubuntu1
charm-tools 2.1.2

bugg@tomsdevbox:~/charms/trusty/joshua-full$ charm whoami
User: spicule
Group membership: charm-contributors

charm push . cs:~apachefoundation/trusty/joshua-full
ERROR cannot post archive: unauthorized: access denied for user "spicule"

I can't login to jujucharms.com but my USSO account does work with launchpad. I've logged out, removed cookies, used 2 different browsers and run charm tools on 2 different machines with the same outcome.

I can push to my local namespace but not my own group.

Now, I have a sneaking suspicion it may be due to a tweak a sysadmin guy did a few months ago when I switched LP names and something was done to facilitate the fact I had charms running into new namespaces. 

Either way I can't login and I can't get charm tools to see my new group..

Help oh great ones!

**Comment by arosales** [comment]
@buggtb added me to lp:~apachefoundation:
https://launchpad.net/~apachefoundation/+members#active

but I don't see this in my group membership after logout/login:
```
arosales@x230:~/devel/big-data/charms/trusty/apache-boilerplate$ date
Tue May 24 15:57:22 PDT 2016
arosales@x230:~/devel/big-data/charms/trusty/apache-boilerplate$ charm version
charm 2:2.1.0-0~ubuntu16.04.1~ppa0
charm-tools 2.1.2
arosales@x230:~/devel/big-data/charms/trusty/apache-boilerplate$ charm logout
arosales@x230:~/devel/big-data/charms/trusty/apache-boilerplate$ charm login
. . 
<redacted>
. . .
arosales@x230:~/devel/big-data/charms/trusty/apache-boilerplate$ charm whoami | grep apachefoundation
arosales@x230:~/devel/big-data/charms/trusty/apache-boilerplate$ 
```

Thus, I can't push to this group:
```
arosales@x230:~/devel/big-data/charms/trusty/apache-boilerplate$  charm push . cs:~apachefoundation/trusty/apache-boilerplate
ERROR cannot post archive: unauthorized: access denied for user "arosales"
arosales@x230:~/devel/big-data/charms/trusty/apache-boilerplate$ 

```
I also tried to create a new team:
https://launchpad.net/~ai-charmers

and I don't see this in my groups either:
```
arosales@x230:~/devel/big-data/charms/trusty/apache-boilerplate$ charm whoami | grep ai-charmers
arosales@x230:~/devel/big-data/charms/trusty/apache-boilerplate$ 

```
I do see prior teams such as charm-contributors though:
```
$ charm whoami | grep bigdata-dev
Group membership: bigdata-dev
$ 
```

Is there a time function on newly created LP teams showing up as groups one can publish to?

-thanks,
Antonio

**Comment by arosales** [comment]
Also, fwiw, https://jujucharms.com/#teams only shows one team for me which is incorrect.

**Comment by marcoceppi** [comment]
This is not a charm tools problem. You need to log out then back in on
jujucharms.com

**Comment by buggtb** [comment]
@arosales did that and failed.

Over here: https://github.com/CanonicalLtd/jujucharms.com/issues/280 @huwshimi says that USSO was in readonly mode which may have effected @arosales . I can't even login to jujucharms.com as my login works but the website just tells me "Sorry for the inconvenience, please pop back soon." so I can't tell if it was caused by USSO in readonly or not.

Tom

**Comment by fabricematrat** [comment]
@buggtb I have sent a request to recreate your identity in jujucharms.com. I will let you know when it is done. You will have then to logout/login from the website jujucharms.com.

@arosales When you are added to a new group you need to logout/login from jujucharms.com, charm logout/login do not fetch the new added group.

**Comment by buggtb** [comment]
@fabricematrat that request has been serviced by someone, I can login now thanks and charm tools can see my group. Thanks for the help!

**Comment by buggtb** [comment]
(Push to apachefoundation group works as well, thanks!)

**Comment by arosales** [comment]
> @arosales When you are added to a new group you need to logout/login from jujucharms.com, charm logout/login do not fetch the new added group.

This is very counter intuitive in how a user would interact with the charm.  I didn't easily connect that I had to login/logout at jujucharms.com (which is odd I have to do that to just recognize groups), and then login/logout with charm tools.  The behaviour I would expect is to see my groups I am added to in jujucharms.com as well as the output of `charm whoami`. I would expect to be able to interface with the charm command independent of jujucharms.

What is the case when someone is doing this all on a server?

**Comment by marcoceppi** [comment]
This issue was moved to juju/charmstore-client#65

**Comment by fabricematrat** [comment]
@arosales this is the situation today,  we will improve that in the next future

**Comment by arosales** [comment]
@fabricematrat 

> @arosales this is the situation today, we will improve that in the next future

Thanks for the update.
