### ISSUE TITLE
Support layers as subdirs of larger repos

### ISSUE THREAD

**Issue by johnsca** [juju/charm-tools#212]
## Checklist
- [X] Confirmed this is an issue with charm-tools, not charmstore-client
- [X] Provide versions of tools used
- [X] Described the feature or ways to replicate the issue
## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm error
charm-tools 2.1.2
```

I am using: Ubuntu / trusty
## Issue/Feature

To enable charms and layers to be part of upstream projects, such as the Apache Bigtop charms, `charm build` should support specifying subdirectories of larger repos for charm, interface, and base layers.  This would also apply to `charm pull-source`.

**Comment by stub42** [comment]
I like the idea in general. A work around may be to use git submodules or git subtrees.

**Comment by stub42** [comment]
The most common case I have is wanting to maintain the interface inside the charm itself (particularly peer interfaces, but also interfaces where we never expect there to be more than one charm providing or requiring it).
