### ISSUE TITLE
charm build -r does not show the interface changes.

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#221]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

```
charm 2.1.1-0ubuntu1
charm-tools 2.1.2
```

I am using: Ubuntu 16.04 (xenial)

## Issue
While doing a `charm build --l DEBUG --series xenial -r` on the etcd layer that had updates to both the local interface and the local layer, the Build Report (-r) did not include the interface changes that were on my local system in the $INTERFACE_PATH directory.

The changes were made, I see them correctly in the built charm directory, I just did not see the files listed in the Build Report.

### I expected the following
I expected to see the updates for both the layer code and the interface code. The report only showed the updates for the layer code and not the local interface that was changed.

I had expected to see:
```
relations/etcd/peers.py
relations/etcd/provides.py
```
in the Build Report

### What I got
```
build: ---------------------------------------
build:               Build Report
build: ---------------------------------------
build:  + .cache/v/cache/lastfailed
build:  + .unit-state.db
build:    templates/defaults
build:    reactive/etcd.py
build:    lib/etcdctl.py
```

**Comment by mbruzek** [comment]
This was verified on my team mate's computer when he did a charm build with the same changes to the interface and the layer code. We did not see the interface changes listed.

**Comment by chuckbutler** [comment]
Whats interesting is i'm able to reliably reproduce the opposing view too where we  *have* the output

```
build: ---------------------------------------
build:               Build Report
build: ---------------------------------------
build:    hooks/relations/etcd/peers.py
build:    hooks/relations/etcd/provides.py
build:    hooks/relations/etcd/requires.py
build:    hooks/relations/etcd/README.md
```

**Comment by chuckbutler** [comment]
and again on the same repo that illustrated the incorrect behavior:

```
ubuntu@devbox:~/layers/etcd$ charm build -r
build: Composing into /home/ubuntu
build: Destination charm directory: /home/ubuntu/builds/etcd
build: Processing layer: layer:basic
build: Processing layer: layer:tls
build: Processing layer: layer:leadership
build: Processing layer: etcd
build: Processing interface: tls
build: Processing interface: etcd
build: Processing interface: etcd
build: Processing interface: etcd-proxy
build:
build: ---------------------------------------
build:               Build Report
build: ---------------------------------------
build:    hooks/relations/etcd/peers.py
build:    hooks/relations/etcd/provides.py
build:    hooks/relations/etcd/requires.py
build:    hooks/relations/etcd/README.md
```

**Comment by chuckbutler** [comment]
Closing until we can reproduce
