### ISSUE TITLE
charm create with a path creates the reactive code in a weird spot

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#239]
## Checklist
- [X] Confirmed this is an issue with charm-tools, not charmstore-client
- [X] Provide versions of tools used
- [X] Described the feature or ways to replicate the issue
## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm 2.1.1-0ubuntu1
charm-tools 2.1.2
```

I am using: Ubuntu
### I expect/expected the following

I issued `charm create /tmp/layers/voting-app` and the script created the reactive file in the wrong location. I got a `/tmp/layers/voting-app/` directory and a `/tmp/layers/voting_app.py` reactive file. Note the python file si not in the correct directory, it shoudl be `/tmp/layers/voting-app/reactive/voting_app.py`
### What I got

```
$ charm create /tmp/layers/voting-app
INFO: Using default charm template (reactive-python). To select a different template, use the -t option.
INFO: Generating charm for /tmp/layers/voting-app in /tmp/layers/voting-app
INFO: No /tmp/layers/voting-app in apt cache; creating an empty charm instead.
Cloning into '/tmp/tmpSRysWJ'...
remote: Counting objects: 22, done.
remote: Total 22 (delta 0), reused 0 (delta 0), pack-reused 22
Unpacking objects: 100% (22/22), done.
Checking connectivity... done.
mbruzek@warhorse:/tmp$ cd layers/
mbruzek@warhorse:/tmp/layers$ ls
voting-app  voting_app.py
mbruzek@warhorse:/tmp/layers$ ls -al
total 24
drwxrwxr-x  3 mbruzek mbruzek  4096 Aug  1 10:51 .
drwxrwxrwt 17 root    root    12288 Aug  1 10:52 ..
drwx------  4 mbruzek mbruzek  4096 Aug  1 10:51 voting-app
-rw-rw-r--  1 mbruzek mbruzek   632 Aug  1 10:51 voting_app.py
```

**Comment by justsostephen** [comment]
The current syntax for specifying a destination path is `charm create <charm-name> <path>`, or, as the help output puts it:
```
usage: charm-create [-h] [-t TEMPLATE] [-a] [-v] [--description]
                    charmname [charmhome]

create a new charm

positional arguments:
  charmname             Name of charm to create.
  charmhome             Dir to create charm in. Defaults to CHARM_HOME env var
                        or PWD
[...]
```
This works for me. As such, can this issue be closed?

**Comment by johnsca** [comment]
I think this was mostly an issue with the template anyway, so yeah, I think it can be closed.
