### ISSUE TITLE
hacking.juju.solutions site can’t be reached  

### ISSUE THREAD

**Issue by tyloch** [juju/charm-tools#245]
There is link to  hacking.juju.solutions in first check point in
PULL_REQUEST_TEMPLATE.md

Unfortunately this site can’t be reached, hacking.juju.solutions’s server DNS address could not be found.

**Comment by marcoceppi** [comment]
The content hasn't been created yet, but it should be.

**Comment by guoqiao** [comment]
Hit the same issue today, +1
