### ISSUE TITLE
Regression: Failure on options in layer.yaml

### ISSUE THREAD

**Issue by bac** [juju/charm-tools#254]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following output:

_It's complicated._

Using the snap:
```
$ which charm
/snap/bin/charm
$ charm version
charm error
charm-tools 2.1.2
```
Using the deb from universe:
```
$ which charm
/usr/bin/charm
$ charm version
charm 2.1.1-0ubuntu1
charm-tools 2.1.2
```

The issue is also present in `master` at `36d72f31dc50ca7fb707697a1608f6c94d0c142e`.
I am using: xenial

## Issue/Feature

Trying to build a charm I get:
```
$ charm build
build: Composing into /home/bac/charms
build: Destination charm directory: /home/bac/charms/builds/bundleservice
build: Processing layer: layer:basic
build: Processing layer: layer:apt
build: Processing layer: layer:nagios
build: Processing layer: bundleservice
build: Processing interface: nrpe-external-master
charmtools.build.tactics: Options set for undefined layer: apt
```
and nothing is created in the `build` directory.

### I expect/expected the following

The charm command should not have complained and the charm should be built.

### What I got

See above.

The error is produced at: 

https://github.com/juju/charm-tools/blob/master/charmtools/build/tactics.py#L516

Debugging I see that `defined_layer_names` includes `layer:basic` and `layer:apt`.  The `option_layer_names` includes `apt` with no 'layer' prefix. This is the crux of the problem.

The layer.yaml file is:

```
includes: ['layer:basic', 'layer:apt', 'layer:nagios', 'interface:nrpe-external-master']
repo: https://github.com/juju/bundleservice-charm.git
options:
  apt:
    packages:
      - bundle service
```

This naming follows the example in 
https://jujucharms.com/docs/2.0/reference-layer-yaml#layer-options

If, however, we temporarily change the name in `options` to `layer:apt` then the charm builds ok.

Also note that if I install version 2.1.4 of charm-tools from pip then I can use `charm-build` and it works as expected.

**Comment by chuckbutler** [comment]
Thanks for the instructions on a workaround @bac, this just bit me today as well

**Comment by mbruzek** [comment]
This bug is very important to the containers team. We can not build any charms with `--no-local-layers` and would really appreciate a fix.
