### ISSUE TITLE
charm-build -l DEBUG should tell me where it found the layer its using

### ISSUE THREAD

**Issue by chuckbutler** [juju/charm-tools#258]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [ ] Provide versions of tools used
 - [ ] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following output:

```
charm error
charm-tools 2.1.2

```

I am using:  Ubuntu 16.04 (snap install charm)

## Issue/Feature

When I charm build -l DEBUG i would expect to see some form of output indicating where the layer came from. Either full path on disk that it located or perhaps the github repository for remote layers coming from the interface API server.

This however doesn't appear to be the case, and debugging incorrect layer inclusions is difficult.

**Comment by mbruzek** [comment]
I second this bug, I see a lot of where the files are copying **TO** but not **FROM** and that kind of information would really help me debug/diagnose problems.
