### ISSUE TITLE
charm-version fails when installed via snap

### ISSUE THREAD

**Issue by johnsca** [juju/charm-tools#264]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm error
charm-tools 2.1.2
```

Output of `snap list charm`:

```
Name   Version  Rev  Developer  Notes
charm  2.2      5    charms     -
```

I am using: Ubuntu Xenial

### I expect/expected the following

`charm-version` should correct report the version of the snap-installed `charm` command as well as the apt-installed version.

### What I got

It instead reports `charm error`.

This is due to [charmtools.version.charm_version](https://github.com/juju/charm-tools/blob/master/charmtools/version.py#L19) only trying apt to find the version.  This could fail, or worse, report an incorrect version.

It should probably detect whether `/snap/bin/charm` or `/usr/bin/charm` is being used (parent process inspection? or just trying one and falling back to the other, I guess) and consult the appropriate system for the version.

**Comment by marcoceppi** [comment]
Fixed in #271
