### ISSUE TITLE
Linting a layer rather than the built artifact

### ISSUE THREAD

**Issue by stub42** [juju/charm-tools#270]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm error
charm-tools 2.1.2
```

I am using: Ubuntu 16.04

## Issue/Feature

When running charm build, I get a lot of bogus warnings

### I expect/expected the following

No bogus warnings

### What I got

Bogus warnings. All the complaints are invalid in the built charm, as the things it is complaining about are pulled in from the base layer or generated from the interface layers:

```
$ charm build --no-local-layers -o ~/charms/repo/
build: Destination charm directory: /home/stub/charms/repo/builds/grafana
build: Processing layer: layer:basic
build: Processing layer: grafana
build: Processing interface: nrpe-external-master
build: Processing interface: grafana-source
build: Processing interface: http
proof: I: no hooks directory
proof: I: relation website has no hooks
proof: I: relation nrpe-external-master has no hooks
proof: I: relation grafana-source has no hooks
proof: I: missing recommended hook install
proof: I: missing recommended hook start
proof: I: missing recommended hook stop
proof: I: missing recommended hook config-changed
```

**Comment by marcoceppi** [comment]
this already exists in the 2.1 tree, but not yet released. I'm cutting a 2.1.5 now with this fix. This was fixed in #256
