### ISSUE TITLE
`deletes` removes config option entirely

### ISSUE THREAD

**Issue by galgalesh** [juju/charm-tools#277]
## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm error
charm-tools 2.1.4
```

I am using: Ubuntu 14.04

### I expect/expected the following

After adding some "deletes" to a `layer.yaml` [as specified in the docs](https://jujucharms.com/docs/2.0/reference-layer-yaml#yaml-modifications) and deploying the charm in a 1.25 environment, I get an error in the charm code that the deleted config options do not exist.

What I expected to happen:

 - the config options still exist, but it are not visible to the user

### What I got

The config option doesn't exist anymore

**Comment by johnsca** [comment]
I'm not sure I understand this bug.  If you delete the config option, it's gone from `config.yaml` and thus won't be valid for the charm code to use.  Juju doesn't have any sort of "hidden" config.

You might be able to get something like this by deleting the config and "patching" the value in to the `hookenv.config()` cache, but it would fail for layers that might use `config-get` directly.

**Comment by galgalesh** [comment]
Thanks for your reply, I thought this worked more like a "hidden" config option. I'm closing this issue.

I'm curious, what is the use-case for `deletes` exactly? It would seem to me that removing config options in an upper layer will always break the lower layers, no?
