### ISSUE TITLE
Generate build manifest with stable ordering

### ISSUE THREAD

**Issue by stub42** [juju/charm-tools#278]
- [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I don't know what versions where used to build the charms.

I am using: (Your operating system)

## Issue/Feature

.build.manifest diffs are unnecessarily large and difficult to read. They could be much more useful as a sanity check of changes. This is probably easily fixed by adding an argument when serializing the data structure.

### I expect/expected the following

.build.manifest should use stable ordering, such as alphabetical, so diffs are smaller and easier to read.

### What I got

Looking at the diff, deletes and inserts are scattered around in a random order so it is non-obvious if a file has been removed, added or changed.

**Comment by marcoceppi** [comment]
.build.manifest is only meant to be machine readable to date. It sounds
like you might want to use the `-r` flag which outputs a build report.

**Comment by stub42** [comment]
A build report is only useful at build time. We are retrospectively diffing revisions on build branches to check for changes in embedded dependencies.
