### ISSUE TITLE
composer/build.yaml duplicates includes

### ISSUE THREAD

**Issue by battlemidget** [juju/charm-tools#28]
This was done with three layers:

- layer:basic
- nodejs
- myapplication

Nodejs layer includes 'layer:basic', my app includes 'layer:basic', when running `charm-compose/build` it states that it processes layer:basic twice:

```
‹master*› »»»» charm-compose                                                                                                 0|20:54:43
composer: Composing into /home/adam/charms
composer: Processing layer: layer:basic
composer: Processing layer: node
composer: Processing layer: layer:basic
composer: Processing layer: wffmapi
composer: Processing interface: pgsql
```

Should this not duplicate by default or should my nodejs layer not include 'layer:basic' and only have the topmost layer include that?

**Comment by marcoceppi** [comment]
Fixed in #29
