### ISSUE TITLE
Charm build removes empty directories

### ISSUE THREAD

**Issue by jacekn** [juju/charm-tools#283]
## Checklist

 - [x] Confirmed this is an issue with charm-tools, not charmstore-client
 - [x] Provide versions of tools used
 - [x] Described the feature or ways to replicate the issue

## What version am I running?

```
$ charm version
charm 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2
charm-tools 2.1.7
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```
## Issue/Feature

I have empty directory in my layer (on purpose):
`files/archive-mirror-scripts/filelists/`

I composed charm using:
`charm build -s xenial`

But above unhelpfully removed the directory without any warning message. In composed charm directory:
`ls: cannot access 'files/archive-mirror-scripts/filelists': No such file or directory`

### I expect/expected the following

I expected `charm build` to preserve empty directories, I created them on purpose, it's much easier to rsync directory tree than create it from python code.
If there is a good reason to modify layers on the fly `charm build` should make it very clear to avoid surprises.

### What I got

`charm build` silently modified my layer without printing any error, warning or info messages. This resulted in broken charm

**Comment by marcoceppi** [comment]
The reason behind this appears to be this chunk of code: [charmtools/build/tactics.py#L200](https://github.com/juju/charm-tools/blob/bf840f57ddd91223c35e05f83370a391fb9affd7/charmtools/build/tactics.py#L200) Where a directory is skipped in preference for an actual file. I'll upload a patch to `makedirs_p` when `entity` is a directory which should resolve this for you.
