### ISSUE TITLE
charm attach should provide progress information

### ISSUE THREAD

**Issue by wwwtyro** [juju/charm-tools#285]
## Checklist

 - [ ] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2
charm-tools 2.1.8
```

I am using: Ubuntu 16.04

## Issue/Feature

It'd be nice if `charm attach` displayed upload progress.

### I expect/expected the following

`[=================>                   ] 60%`

### What I got

Literally nothing. Zero feedback until the upload is complete, which can take a while depending on uplink/filesize. Is it frozen? You don't know!

![giphy](https://cloud.githubusercontent.com/assets/929443/20395670/57a1104a-aca9-11e6-8c97-832e72c51f9a.gif)

**Comment by johnsca** [comment]
`charm attach` is implemented in https://github.com/juju/charmstore-client

**Comment by marcoceppi** [comment]
This issue was moved to juju/charmstore-client#99
