### ISSUE TITLE
Charm build creates duplicated `series` entries

### ISSUE THREAD

**Issue by galgalesh** [juju/charm-tools#297]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2
charm-tools 2.1.9

```

I am using: Ubuntu 16.04

### I expect/expected the following

When building a charm that has two layers that both include a `metadata.yaml` file with the `series` field, the `series` of the top-level layer should be used in the final Charm

### What I got

The `series` field got merged, resulting in duplicated series:

    series: ['xenial', 'trusty', 'xenial', 'trusty']

Charms with series fields such as this break the charm store. See https://lists.ubuntu.com/archives/juju/2017-January/008416.html

**Comment by marcoceppi** [comment]
Thanks for the report, working on a patch now

**Comment by galgalesh** [comment]
Thanks Marco! When's the next charm-tools release?

**Comment by marcoceppi** [comment]
Right now!

**Comment by galgalesh** [comment]
:+1:
