### ISSUE TITLE
charm-tools from the juju/stable ppa is not installable on trusty

### ISSUE THREAD

**Issue by vilagithub** [juju/charm-tools#303]
On a fresh trusty host, with the ppa:juju/stable https://launchpad.net/~juju/+archive/ubuntu/stable/

apt-get install charm-tools fails with:

The following packages have unmet dependencies:
 charm-tools : Depends: python-libcharmstore (>= 0.0.3) but it is not installable

The last libcharmstore upload for trusty  https://launchpadlibrarian.net/295590003/buildlog_ubuntu-trusty-i386.libcharmstore_0.0.6-0ubuntu1~ubuntu14.04.1~ppa2_BUILDING.txt.gz failed with:

make[1]: /bin/nosetests: Command not found

**Comment by chuckbutler** [comment]
@vilagithub - if you're not opposed to trying something new, charm + charm-tools have refocused under snaps. Snapd is now installable on trusty, and you can test this path which should have you running the latest and greatest of the developer tooling in a nice auto-refreshing fashion under snaps

```
sudo apt-get install -y snapd 
sudo apt purge charm charm-tools (respectively)
sudo snap install charm --classic
```

If you encounter any issues here we'd love to hear the feedback on how this went for you and if this resolved your issue with the current apt-package. I do beleive the deb is a few releases behind the snap package, and efforts have been doubled on focusing on the snap path as charm-tools is a fast moving project.

**Comment by vilagithub** [comment]
That doesn't seem to work inside an lxd container which is where I need  it :-/

$ sudo snap install charm --classic
error: cannot communicate with server: Post http://localhost/v2/snaps/charm: dial unix /run/snapd-snap.socket: connect: no such file or directory

**Comment by nskaggs** [comment]
@vilagithub install squashfuse in the container first; it should work.

Also see https://bugs.launchpad.net/snappy/+bug/1611078

**Comment by shawn111** [comment]
Hello,

I run charm(snap) on trusty, but got below issue.
It only happened on trusty, but good on xenial.

$ charm build
Traceback (most recent call last):
  File "/snap/charm/11/bin/charm-build", line 7, in <module>
    from charmtools.build.builder import main
  File "/snap/charm/11/lib/python2.7/site-packages/charmtools/build/__init__.py", line 6, in <module>
    from builder import (
  File "/snap/charm/11/lib/python2.7/site-packages/charmtools/build/builder.py", line 16, in <module>
    from charmtools import (utils, repofinder, proof)
  File "/snap/charm/11/lib/python2.7/site-packages/charmtools/proof.py", line 23, in <module>
    from charms import Charm
  File "/snap/charm/11/lib/python2.7/site-packages/charmtools/charms.py", line 13, in <module>
    from launchpadlib.launchpad import Launchpad
  File "/snap/charm/11/lib/python2.7/site-packages/launchpadlib/launchpad.py", line 33, in <module>
    from httplib2 import proxy_info_from_environment
  File "/snap/charm/11/lib/python2.7/site-packages/httplib2/__init__.py", line 930, in <module>
    class HTTPSConnectionWithTimeout(httplib.HTTPSConnection):
AttributeError: 'module' object has no attribute 'HTTPSConnection'

**Comment by vilagithub** [comment]
According to https://bugs.launchpad.net/snappy/+bug/1628289/comments/18 using the charm snap in a trusty container is a no-go.

Is there a way to un-break trusty support in the https://launchpad.net/~juju/+archive/ubuntu/stable/ ppa while we migrate to xenial/snaps in the various affected environments ?

**Comment by chuckbutler** [comment]
cc @marcoceppi on this issue. It looks like despite our best efforts we have an orphaned package.

**Comment by arosales** [comment]
The other issue this brings up is Travis testing is also failing as they only offer Trusty buids, aiui Travis doesn't include Xenial testing atm.

**Comment by johnsca** [comment]
@arosales is correct that [Travis doesn't support Xenial](https://github.com/travis-ci/travis-ci/issues/5821).  We also ran in to [an issue](https://github.com/travis-ci/travis-ci/issues/7318) trying to use the snap in Travis, so we're completely blocked on this now for getting passing Travis builds.

**Comment by vilagithub** [comment]
For the record, https://launchpad.net/~ubuntuone/+archive/ubuntu/charm-tools now has *trusty* versions working for charm-tools and libcharmstore so we're out of trouble until we migrate to either xenial or the snap.

**Comment by marcoceppi** [comment]
An update python-libcharmstore is now in the stable ppa (thanks @vilagithub)
