### ISSUE TITLE
`charm create` templates still using squircles

### ISSUE THREAD

**Issue by cmars** [juju/charm-tools#307]
`charm create` templates are using the old "squircle" SVG icons. These don't work very well with the GUI now. I think the charm author should now just use any old SVG icon, it will get centered in a circle.

This, for example, is wrong:

https://github.com/juju/charm-tools/blob/master/charmtools/templates/bash/files/icon.svg

**Comment by makyo** [comment]
With the caveat that the generated SVG needs a viewBox. I believe Inkscape does this automatically, but will need to check.

**Comment by marcoceppi** [comment]
We were told the GUI would clip. If it's not, then there's a bug with the
GUI.

**Comment by makyo** [comment]
@marcoceppi The GUI does clip, as does the charmstore. We're saying that, per design, icons are no longer expected to have the shaded squircle. Cf: https://api.jujucharms.com/charmstore/v5/~containers/easyrsa-6/icon.svg vs https://api.jujucharms.com/charmstore/v5/~leostream-vdi/leostream-broker-4/icon.svg

**Comment by makyo** [comment]
Submitted too early. The result of clipping is: https://jujucharms.com/u/leostream-vdi/leostream-broker/4
