### ISSUE TITLE
charm-build fails to start in latest snap install on xenial

### ISSUE THREAD

**Issue by cholcombe973** [juju/charm-tools#308]
Version: charm  2.2      11    charms     classic
16.04 xenial amd64 desktop.  Installed the charm snap with: `sudo snap install charm --classic`
Change directory to a layer charm and try to build:
```
/snap/charm/current/bin/charm-build version
Traceback (most recent call last):
  File "/snap/charm/current/bin/charm-build", line 7, in <module>
    from charmtools.build.builder import main
ImportError: No module named charmtools.build.builder
```

## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [x] Provide versions of tools used
 - [x] Described the feature or ways to replicate the issue

I am using: Ubuntu 16.04.2 LTS \n \l
4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I expected the layer charm to build.  Unless I missed something obvious it seems like the snap is broken.

**Comment by johnsca** [comment]
This was resolved some time ago by switching to strict confinement.
