### ISSUE TITLE
`charm` command missing `promulgate` from the snap package

### ISSUE THREAD

**Issue by chuckbutler** [juju/charm-tools#310]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm 2.2.0
charm-tools 2.2.0
```

I am using: 
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```
## Issue/Feature

charm promulgate is missing from the snap package

### I expect/expected the following

charm promulgate to be a valid command

### What I got

charles@makoto:~$ charm promulgate
ERROR unrecognized command: charm promulgate

**Comment by johnsca** [comment]
I am not aware of any plans to add the promulgate command to the `charm` snap, but if it were, it would be done in the go portion of the tool, [charmstore-client](https://github.com/juju/charmstore-client/issues).  Closing this here, but feel free to re-open there if you think it should be.
