### ISSUE TITLE
Migrate from interfaces.juju.solutions to a GitHub repo

### ISSUE THREAD

**Issue by johnsca** [juju/charm-tools#324]
The layer index site works, but was originally intended to be an interim to finding a more permanent solution.   It has not, however, been improved or replaced.  It is also confusing for users in that it is separate from both the charm store and the code base.  Instead of maintaining an active index site & API, we should use a GitHub repo to manage the layer index.  This would allow us to use PRs for managing the index, giving more visibility to the community when layers are added, modified, or removed.

I think we should probably have a YAML file per record in the current database, and we might want to include some script or hook for updating a Markdown index (perhaps a subsection of the README.md) with clickable links to the repos referenced in the YAML files.

**Comment by marcoceppi** [comment]
I suggest charms/charm-layers as a repo for this?

**Comment by johnsca** [comment]
I originally thought it would be nice to have the layer repos pulled in as submodules, with the option of some smaller layers being embedded directly in the index repo.  However, submodules have a host of issues that make them unsuitable to this task, such as the inability to reference subdirectories in the submodule's repo, and requiring manual intervention in the parent repo to pull in updates to the submodules.  Still, being able to leverage the GitHub UI to automatically click through to child repos and being able to clone the entire set of layers locally is appealing.

**Comment by johnsca** [comment]
@marcoceppi I thought we were trying to consolidate everything under the [juju](/juju) namespace?

**Comment by marcoceppi** [comment]
I think charms work as an independant org. I don't like the submodules
route, it's messy

**Comment by battlemidget** [comment]
Not sure about the independent org though but I dont have any opinions on that either way
