### ISSUE TITLE
charm create from snap fails: OSError: [Errno 2] No such file or directory: '/tmp/tmpOx6ca0'

### ISSUE THREAD

**Issue by dannf** [juju/charm-tools#327]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
$ charm version
charm 2.2.2
charm-tools 2.2.1
```

I am using: Debian GNU/Linux

## Issue/Feature
charm create fails.
### I expect/expected the following
No crash.

### What I got
```
$ charm create java-browser
INFO: Using default charm template (reactive-python). To select a different template, use the -t option.
INFO: Generating charm for java-browser in ./java-browser
INFO: No java-browser in apt cache; creating an empty charm instead.
Cloning into '/tmp/tmpOx6ca0'...
fatal: Unable to find remote helper for 'https'
Traceback (most recent call last):
  File "/snap/charm/15/bin/charm-create", line 11, in <module>
    sys.exit(main())
  File "/snap/charm/15/lib/python2.7/site-packages/charmtools/create.py", line 98, in main
    generator.create_charm()
  File "/snap/charm/15/lib/python2.7/site-packages/charmtools/generators/generator.py", line 77, in create_charm
    self._cleanup(tempdir)
  File "/snap/charm/15/lib/python2.7/site-packages/charmtools/generators/generator.py", line 127, in _cleanup
    shutil.rmtree(tempdir)
  File "/snap/charm/15/usr/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/snap/charm/15/usr/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/tmpOx6ca0'
```

**Comment by deephack1982** [comment]
Can confirm the same here. Juju and Charm tools installed from snap packages.

Ubuntu 17.04
charm 2.2.2
charm-tools 2.1.2

`$ charm create -v paradox-linux-buildslave-puppet
INFO create.py: Using default charm template (reactive-python). To select a different template, use the -t option.
INFO generator.py: Generating charm for paradox-linux-buildslave-puppet in ./paradox-linux-buildslave-puppet
INFO utils.py: No paradox-linux-buildslave-puppet in apt cache; creating an empty charm instead.
Cloning into '/tmp/tmpCsS6xP'...
fatal: unknown error occured while reading the configuration files
Traceback (most recent call last):
  File "/snap/charm/17/bin/charm-create", line 11, in <module>
    load_entry_point('charm-tools==2.1.2', 'console_scripts', 'charm-create')()
  File "/snap/charm/17/lib/python2.7/site-packages/charmtools/create.py", line 98, in main
    generator.create_charm()
  File "/snap/charm/17/lib/python2.7/site-packages/charmtools/generators/generator.py", line 77, in create_charm
    self._cleanup(tempdir)
  File "/snap/charm/17/lib/python2.7/site-packages/charmtools/generators/generator.py", line 127, in _cleanup
    shutil.rmtree(tempdir)
  File "/snap/charm/17/usr/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/snap/charm/17/usr/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/tmpCsS6xP'`

**Comment by johnsca** [comment]
I'm not able to reproduce this, but in both cases it seems to have failed to download the template and then blown up in the cleanup code.  We definitely need to fix the cleanup code and should ensure that template fetch errors are reported better with more useful debugging info.

**Comment by johnsca** [comment]
It seems that both original failures are git errors so the cause may depend on the particular template used (though both seem like they should use the default) or some file in the current directory or in the snap causing odd behavior from git.

Also, the version reported in the initial report doesn't match what I see from any channel from the snap store.

**Comment by deephack1982** [comment]
Yes, the wording is identical to a common git error. I'm wondering if there is something wrong with my snap setup as I initially installed charm-tools and juju via the ppa. I'll investigate my setup and see if I can straighten it out and then re-test.

I'll report back today.

**Comment by deephack1982** [comment]
Okay got to the bottom of this. By default the snap package is using strict confinement and so has no access to anything outside of the snaps own directory's. I re-installed it using "sudo snap install charm --classic" and now everything works normally. The documentation does state that juju should be installed with the --classic flag but not charm, perhaps this should be changed.

**Comment by johnsca** [comment]
The documentation is out of date and `--classic` should **not** be used, as it leads to issues like #339.  The strictly confined snap does have access to non-hidden files and directories under `$HOME` so must be run somewhere under `$HOME`.  There was a release announcement on the Juju mailing list that discussed this.

The snap shouldn't need access to anything outside of it's internal file system other than the output directory.  The git command it uses is built with the snap, and the cloning that it does to get the templates is on the snaps isolated file system.  In theory, nothing in the environment should be affecting that process, which means that it should be easily repeatable regardless of environment.  Unfortunately, I'm not able to repeat it using any of the current channels of the snap (edge, beta, candidate, nor stable), which means it's either being caused by some specific aspect of how it's being called that I'm not seeing in the bug report, or there's some environmental aspect that is still causing an issue somehow.

Please confirm that you are calling `charm create` from somewhere under `$HOME` and using the latest snap from one of the charm store channels with strict confinement.  Please include the snap revision number from `snap info charm` and the full command that you use to replicate the issue.  Thank you.

**Comment by johnsca** [comment]
Actually, I checked, and I couldn't find anywhere in [the docs](https://jujucharms.com/docs/stable/tools-charm-tools#ubuntu) or the [README](https://github.com/juju/charm-tools#get-charm-tools) that say to use `--classic`.

**Comment by deephack1982** [comment]
I just intended to point out that the README says to install juju with --classic but not charm. My finding is though that unless I use --classic I cannot build or create using the charm tool.

I've remove and re-installed the charm with strict confinement but it still doesn't work. It looks like something is up with my workstations install of Ubuntu though as I created a Virtualbox with a fresh install of Ubuntu 16.04 and another with 17.04. On both test vms everything is working fine.

I'm going to re-install on my workstation and I'll let you know if the problem goes away.

**Comment by johnsca** [comment]
Sorry, misread that.  Juju does indeed require classic confinement, although I think the goal is eventually to resolve that as well. 

The whole point of switching to strict confinement for the `charm` snap was to avoid environmental conflicts, so I'd really like to get to the bottom of this.  Can you confirm that you were building entirely under `$HOME`?
