### ISSUE TITLE
add --clean flag to charm build

### ISSUE THREAD

**Issue by chuckbutler** [juju/charm-tools#33]
When heavily developing a charm, there are cases where I'm shuffling interfaces/layers between the dependent layer.yaml(s) - and as charm-build is a constructive tool, there's no easy way to signal in place "Please remove my prior constructed charm, and rebuild from scratch - i've removed something".

Introducing a --clean flag is indicative that its a destructive process, and as charm-build knows where the file is going, it could reasonably rm -rf the directory prior to doing the build to ensure a clean artifact is constructed.

**Comment by johnsca** [comment]
I don't think that we should just `rm -rf` the target directory, as it may be version controlled (until `juju publish` is available).  However, it certainly could detect and remove any files that are no longer signed by the manifest.

Even better would be to have it explicitly track files that were in the previous manifest and remove them if they are not in the new manifest, which seems like it could be reasonably done by default (i.e., without `--clean`).

**Comment by marcoceppi** [comment]
+1

**Comment by chuckbutler** [comment]
I agree with this as well :+1:
