### ISSUE TITLE
Feature req: support pulling layers from github/bitbucket etc

### ISSUE THREAD

**Issue by battlemidget** [juju/charm-tools#34]
Not sure the scope of this but it would be nice to have something like this in my `layer.yaml`

```yaml
includes: ['layer:battlemidget/nodejs']
```

Or maybe even further
```yaml
includes: ['interface:bb:battlemidget/apache2', 'interface:gh:battlemidget/rethinkdb']
```

Or with the latest charm-tools `layer.yaml` and `interface.yaml` it could be shortened to

```yaml
# layer.yaml
includes: ['gh:battlemidget/nodejs']
```
Or

```yaml
# interface.yaml
includes: ['bitbucket/battlemidget/rethinkdb']
```

Kind of like scoped packages that don't necessarily need to be pushed into the main http://interfaces.juju.solutions. Could possibly use the same interface for launchpad as well

```yaml
includes: ['lp/adam-stokes/nodejs']
```

**Comment by marcoceppi** [comment]
What advantage would you gain with this? What scenario would you want to have a layer that wasn't in the index?

Seems better to expand the index to allow for the idea of curated vs personal layers much like we do with charms rather than grow the complexity of where to find layers

**Comment by battlemidget** [comment]
Im probably just being impatient, how far along until the list is automatically curated?

**Comment by marcoceppi** [comment]
Well you can upload layers now, its open to the world. The curation is
something that I just came up with as an alternative, not actually on
roadmap atm

**Comment by battlemidget** [comment]
Ah didn't realize it was opened, last I checked the login with LP didn't work.
