### ISSUE TITLE
Stable snap doesn't work on trusty

### ISSUE THREAD

**Issue by johnsca** [juju/charm-tools#343]
Installing current stable charm snap on trusty and trying to run any of the subcommands gives:

```
cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied
```

**Comment by johnsca** [comment]
Ah, nevermind.  Apparently, the unit needed to be rebooted.

**Comment by markstos** [comment]
@johnsca Which unit? What was the command you used? Thanks.

**Comment by johnsca** [comment]
If I recall correctly, this appeared to just be an issue with the snap daemon after first install.  So it's advisable after using `sudo apt install snapd` on trusty, to reboot the machine before attempting to install or use any snaps.
