### ISSUE TITLE
Minor error with "charm build" in a gnu screen session

### ISSUE THREAD

**Issue by petevg** [juju/charm-tools#344]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm 2.2.2
charm-tools 2.1.2
```

I am using: ubuntu/xenial

When run "charm build" in a Gnu Screen session, it fails with the following error:
```

Traceback (most recent call last):
  File "/snap/charm/17/bin/charm-build", line 11, in <module>
    load_entry_point('charm-tools==2.1.2', 'console_scripts', 'charm-build')()
  File "/snap/charm/17/lib/python2.7/site-packages/charmtools/build/builder.py", line 671, in main
    configLogging(build)
  File "/snap/charm/17/lib/python2.7/site-packages/charmtools/build/builder.py", line 579, in configLogging
    blessings.Terminal(),
  File "/snap/charm/17/lib/python2.7/site-packages/blessings/__init__.py", line 105, in __init__
    self._init_descriptor)
_curses.error: setupterm: could not find terminal
```

This is not difficult to work around. I inspected the value of TERM in my environment, and saw that it was "screen.xterm-256color". I changed the value of TERM to "xterm-256color", and the command worked. It would be nicer if the tool simply ignored the "screen." part of a terminal declaration, however.

**Comment by petevg** [comment]
I was poking at this a bit. It looks like a bug in the blessings lib at first read through the traceback, but when I try to just use blessings in a screen session, outside of the context of the charm tools, it works fine. I can create a Terminal object.

"charm build" still produces the error, though, and it looks like I've got a current version of it (freshly snap installed), with an up-to-date version of the blessing lib.

**Comment by petevg** [comment]
After poking at this some more, it appears to only happen while inside of the snap.

I've also tested with a snap built locally from the latest trunk, so it's not an issue of the current snap being behind.

**Comment by szeestraten-ntnu** [comment]
Ran into the same issue where I'm hitting it from running `bundletester` in `tox`. Workaround for me was to add: `passenv = HOME TERM`.
