### ISSUE TITLE
Unclear distribution channels and versioning for charm-tools

### ISSUE THREAD

**Issue by szeestraten-ntnu** [juju/charm-tools#357]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `snap info charm` and got the following ouput:

```
$ snap info charm
name:      charm
summary:   "charm and charm-tools"
publisher: charms
contact:   juju at lists.ubuntu.com
description: |
  charmstore-client and charm-tools
snap-id: 2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
commands:
  - charm
tracking:    stable
installed:   2.2 (17) 102MB -
refreshed:   2017-07-31 18:40:23 +0000 UTC
channels:
  stable:    2.2 (17) 102MB -
  candidate: 2.2 (23) 102MB -
  beta:      ↑
  edge:      2.2 (37) 102MB -
```

I am using: Ubuntu 16.04.3 LTS

## Issue/Feature

Adding in from mailing list, https://lists.ubuntu.com/archives/juju/2017-October/009553.html, so it can be tracked here.

> Hey folks,

> I'm having a bit of a hard time figuring out which distribution of
charm-tools I can/should use and how they are versioned in order to keep
track of bugfixes.

> As far as I understand, the snaps are preferred over the packages in the
Juju PPA and PyPI falls somewhere in between?

> The snap channels all refer to 2.2 which makes it a bit difficult to tell
which are which (see below), yet they all display charm 2.2.2 and
charm-tools 2.1.2 when running "charm version". I'm sure I'm missing
something obvious but how do I keep track of what is in each snap build?

> Finally, we're using bundletester for running tests which pulls inn
charm-tools from PyPI which seems to have 2.2.0 as the latest version. Does
PyPI still get new charm-tools releases? If not, what's the recommended
workflow for those running bundletester?

> P.S. The page on PyPI still refers to installing charm-tools from the Juju
PPA which probably should be fixed.

**Comment by johnsca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [charm-tools versioning](https://trello.com/c/VBOVc3Vu/97-charm-tools-versioning)

**Comment by szeestraten-ntnu** [comment]
Any update on this?

**Comment by johnsca** [comment]
2.2.3 has been released to the stable snap channel and to PyPI, so it should be clear now that the snap is the preferred installation mechanism with PyPI being up to date.

**Comment by szeestraten-ntnu** [comment]
Great. I also see that the snap channels have proper version numbering now which helps a lot. Thanks @johnsca!
