### ISSUE TITLE
base layer hooks hardcode Python2

### ISSUE THREAD

**Issue by stub42** [juju/charm-tools#37]
The install, upgrade-charm, start, stop etc. hooks in the reactive basic layer all use '#!/bin/env python' as the shebang line, which is Python2. Rather than force a version of Python that has been deprecated for several years and will soon stop being on the cloud images by default, 'charm build' should default to generating Python3 stubs and perhaps provide an option to use Python2 when compatibility is needed with legacy code.

layer.yaml could be used to declare if Python2 compatibility is needed.

If both Python2 and Python3 are supported, 'charm build' will need to detect and correct shebang lines somehow. The edge case here being a Python3 charm that includes copies of legacy Python2 scripts (eg. administrative scripts to be invoked from cron).

**Comment by stub42** [comment]
Python2 is scheduled for removal in Ubuntu 16.04, at which point '/bin/env python' will stop working unless we can work out a way to bootstrap Python2. I'm unsure if Python2 will remain in main, or be moved to universe and potentially uninstallable in some environments. Maybe a reason for Python3 only? Charms will need to be reworked for the reactive framework in any case.

**Comment by johnsca** [comment]
#55 switches to Python 3 by default
