### ISSUE TITLE
charm commands fail when operating in /tmp

### ISSUE THREAD

**Issue by dannf** [juju/charm-tools#371]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `snap info charm` and got the following ouput:

```
name:      charm
summary:   "charm and charm-tools"
publisher: charms
contact:   juju@lists.ubuntu.com
description: |
  charmstore-client and charm-tools
snap-id: 2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
commands:
  - charm
tracking:    edge
installed:   2.2.3 (114) 103MB -
refreshed:   2017-11-01 20:23:28 -0600 MDT
channels:                
  stable:    2.2.3 (114) 103MB -
  candidate: 2.2.3 (114) 103MB -
  beta:      ↑                 
  edge:      2.2.3 (114) 103MB -
```

I am using: Debian GNU/Linux unstable (sid)

## Issue/Feature
Commands fail with unclear error when referencing /tmp.

### I expect/expected the following
If I run charm commands (proof, push, etc) from a subdir of my home directory, I get expected results:
```
dannf@xps13:~/openstack-base$ charm proof
dannf@xps13:~/openstack-base$
```
### What I got
However, if the same charm/bundle is under /tmp - which I use quite heavily for ephemeral content - it fails:
```
dannf@xps13:/tmp/openstack-base$ charm proof
FATAL: No bundle.yaml (Bundle) or metadata.yaml (Charm) found, cannot proof
```

**Comment by johnsca** [comment]
This is due to the fact that the snap is now strictly confined, and strictly confined snaps can only access non-dot files and directories under the user's home.

We should, however, report this explicitly, as we do for `charm build` and `charm create`.
