### ISSUE TITLE
Juju test plugin no longer installed

### ISSUE THREAD

**Issue by devec0** [juju/charm-tools#374]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `snap info charm` and got the following ouput:

```
name:      charm
summary:   charm and charm-tools
publisher: charms
contact:   juju@lists.ubuntu.com
description: |
  charmstore-client and charm-tools
snap-id: 2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
commands:
  - charm
tracking:    stable
installed:   2.2.3 (114) 103MB -
refreshed:   2017-11-02 03:23:28 +0100 CET
channels:                                   
  stable:    2.2.3                    (114) 103MB -
  candidate: 2.2.3                    (114) 103MB -
  beta:      ↑                                    
  edge:      2.2.4-dev+git-0-g716db46 (115) 103MB -
```

I am using: Ubuntu Bionic Beaver 18.04

### I expect/expected the following

Charm tools formerly implemented the "juju test" command. It is still present in the 'test.py' file in this repository, but there appears to be no binary pointing to it exposed by the snap.

Either a binary 'juju-test' to perform as a juju plugin (best for backward compatibility with existing Makefiles) or a new CLI option "charm test" should reference this code.

### What I got

```
└─▪ juju test
ERROR unrecognized command: juju test
```

**Comment by devec0** [comment]
I have opened #375 to address

**Comment by johnsca** [comment]
The test plugin was removed because it was deprecated in favor of [zaza](https://zaza.readthedocs.io/en/latest/) or plain [python-libjuju](https://pythonlibjuju.readthedocs.io/en/latest/) for running charm tests, as they are more robust, featureful, and maintained.
