### ISSUE TITLE
chef templates

### ISSUE THREAD

**Issue by battlemidget** [juju/charm-tools#379]
Bringing in activesupport/all is typically not a good idea. They are compartmentalized so that you can pick and choose certain features to pull into your ruby code.

In reviewing the current ruby code in charm-tools I only see one place where activesupport is used, and that's with their `try` method (http://guides.rubyonrails.org/active_support_core_extensions.html#try)

You can easily replace this with an unless (as seen in that link above). We should update the code to do away with bringing in activesupport or only bring in certain features required for functionality of this portion of the code. I don't think the extension of `try` to all objects in Ruby warrants us bringing in something as heavy as activesupport.

I dont know what the effects are if we remove activesupport (not sure who uses chef in their charms) but we should try to keep the ruby dependencies at a minimal at least until Trusty reaches EOL (as newer releases contain Ruby 2+)

**Comment by marcoceppi** [comment]
I have a pretty I'm pushing that will remove these templates as they are basically broken

**Comment by marcoceppi** [comment]
Yes, just in transit, give me 60 mins.

**Comment by johnsca** [comment]
Fixed by #380
