### ISSUE TITLE
Installation of dependencies undocumented

### ISSUE THREAD

**Issue by stub42** [juju/charm-tools#38]
The base layer appears to magically install Python depencies using .pypi files in the lib/ directory. This mechanism appears to be undocumented. Is this for general use, or only for charm-tools to get itself bootstrapped?

**Comment by johnsca** [comment]
The current handling of `.pypi` files was intended for internal / bootstrapping and not for general use.  There are also several issues with how they are handled wrt. doing the library install during the build process to vendor the library in.  I plan to change that very soon to instead build a wheelhouse that is installed during the install hook.  We may decide to document it at that point and open it up for general use, but we also don't particularly want to encourage "fat" charms with lots of bundled libs; the better solution there is resources support in Juju core.
