### ISSUE TITLE
charm-layers to have a minimal flag

### ISSUE THREAD

**Issue by battlemidget** [juju/charm-tools#39]
Running `charm-layers` pretty much dumps the tree of what a final charm looks like from `charm-build`

http://paste.ubuntu.com/13094417/

It would be nice to have a flag like `--no-deps` to only print the files I've actually created and not those installed via pip in the `/lib` dir.

**Comment by johnsca** [comment]
I'd prefer to address this by bringing in those bootstrap deps as wheels instead of full "installed" directories in the built charm.

**Comment by battlemidget** [comment]
That would be better and could potentially be labeled as 'dependencies' rather than being in the overall file list tree

**Comment by marcoceppi** [comment]
@battlemidget could you try with 1.9.3 and the new wheelhouse approach? I think this will resolve the mile long dep tree

**Comment by battlemidget** [comment]
Yea this is resolved with 1.9.3
