### ISSUE TITLE
discussion around utilizing config.yaml options

### ISSUE THREAD

**Issue by battlemidget** [juju/charm-tools#40]
One thing I'm noticing while developing layers is that while the config.yaml options bubble up to the topmost layer you can run into issues where config options may get merged if their keys are the same. For example, a `port` which could be a setting in an `nginx` layer, and a setting in `yourapplication` layer if setup to utilize the reverseproxy.

The way i've currently dealt with it is to prefix my config options, so for example, nginx I have `nginx-port`, and my web application will then have `mywebapp-port`.

Depending on the amount of layers you have this could lead to more headache trying to manage those config options from several layers. This should probably rarely be an issue as the amount of layers used per charm would be minimal I thought it'd be something to think about for documentation.

**Comment by johnsca** [comment]
I believe that config options are eventually going to support the same more complex syntax that action parameters use, which will enable nesting / namespacing of options.  This should address this in a natural way, but in the meantime I think that adopting a convention of prefixing option names with the layer name (in much the same way that we have a loose convention to have files in `reactive/` named the same as the layer) the way you suggested should help.

**Comment by bcsaller** [comment]
The config space is the domain of the operator, not the charm author. We
shouldn't bleed implementation details into the names of the options they
are setting. If the base layer is providing options that are too incorrect,
you can override them, if you don't know what it is providing then create
the layers.yaml file with your includes and run 'charm build' and look at
the output.

If this is a frequent issue (unintentional overrides of a previous layer
config) we can issue warnings during merge, but for the most part I'd
assume this was an intentional override.

**Comment by johnsca** [comment]
I think what @bcsaller is getting at is that if we're running into conflicts in config options that aren't correctly resolved by accepting the higher layer's version, then it might mean the option isn't worthwhile to expose to the end user (Juju admin).

In particular, for this example, if the webapp is being proxied behind nginx, then it doesn't really make sense to expose the port it's listening on as a config option, as that value is only useful to facilitate communication between nginx and the webapp.  Instead, the charm or app should just choose a high, unused port (or have a default that is unlikely to conflict) and send that to nginx.

**Comment by battlemidget** [comment]
So for example, Ghost defaults its port to `2638`. With that should I just hardcode in the default into the proxy configuration for nginx?

**Comment by marcoceppi** [comment]
I think the point here is not that the user cares what nginx runs at and
what the app, simply how to get to the service. So how the internal
plumbing lines up is irrelevant. The user should just set a port and the
charm should just work

**Comment by battlemidget** [comment]
Fair enough, makes sense, thanks!
