### ISSUE TITLE
Resources cannot be optional

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charm-tools#439]
A charm needs to be able to define a resource in metadata.yaml as optional.

```
ERROR cannot release charm or bundle: resources are missing from publish request: theme
```

There are currently two production cases which require this:

openstack-dashboard optional theme files
vault optional alternate binary package

Currently, a user is expected to publish a 0kb resource blob to work around this, which is ok (yet awkward) for one-off human charm store interactions. But is thorny to think about automating that across 40+ charms in a collective product where resource implementation is the exception (optional) rather than the norm.

References:

https://bugs.launchpad.net/charm-openstack-dashboard/+bug/1778284

**Comment by ryan-beisner** [comment]
See also:
https://github.com/CanonicalLtd/jujucharms.com/issues/546

**Comment by johnsca** [comment]
Unfortunately, this is being rejected by the charm store and not the client:

```
[johnsca@murdoch:~/juju/envs/dev] $ charm release --channel=edge cs:~johnsca/test-1 --debug
11:48:58 DEBUG httpbakery logger.go:28 client do PUT https://api.jujucharms.com/charmstore/v5/~johnsca/test-1/publish {
11:48:58 INFO  httpbakery logger.go:33 HTTP response OK (status 400 Bad Request)
11:48:58 DEBUG httpbakery logger.go:28 } -> error <nil>
ERROR cannot release charm or bundle: resources are missing from publish request: test
11:48:58 DEBUG cmd supercommand.go:475 error stack: 
resources are missing from publish request: test
gopkg.in/juju/charmrepo.v4/csclient/csclient.go:1007: 
gopkg.in/juju/charmrepo.v4/csclient/csclient.go:603: 
github.com/juju/charmstore-client/cmd/charm/charmcmd/release.go:111: cannot release charm or bundle
```

There is nothing that can be done in the client (which would technically be in charmstore-client anyway, but that's moot).
