### ISSUE TITLE
Relative paths don't work with charm build in the output flag.

### ISSUE THREAD

**Issue by kat-co** [juju/charm-tools#44]
[This](https://github.com/kat-co/elnode-charm/blob/master/Makefile#L4) is effectively using a relative path to direct output to a distribution folder. Through working with @bcsaller @marcoceppi @johnsca and @mbruzek, we discovered that this fails to produce a bin directory in the generated charm.

@bcsaller has asked that I assign this to him.

**Comment by johnsca** [comment]
This is quite possibly resolved with #54.
