### ISSUE TITLE
Impossible to use "charm layers"

### ISSUE THREAD

**Issue by stnbu** [juju/charm-tools#450]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `snap info charm` and got the following output:

```
name:      charm
summary:   charm and charm-tools
publisher: Cory Johns (johnsca)
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     stable
refresh-date: today at 12:37 PDT
channels:
  stable:    2.2.5                (176) 42MB -
  candidate: 2.2.5                (176) 42MB -
  beta:      2.3.1                (212) 46MB -
  edge:      2.3.1+git-5-g04ca207 (233) 47MB classic
installed:   2.2.5                (176) 42MB -
```

I am using:

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

## The issue: `charm layers` always fails

If I run `charm layers`, I get the following error:

```
charm layers ./mycharm
build: For security reasons, only paths under your home directory can be accessed
```

`./mycharm` is under my home directory. I looked at the code and it appears this will always fail.

[This line](https://github.com/juju/charm-tools/blob/484538d79a6b0efca404b3977cff9fe861a6e7df/charmtools/build/builder.py#L639) uses the return value of [_check_path()](https://github.com/juju/charm-tools/blob/484538d79a6b0efca404b3977cff9fe861a6e7df/charmtools/build/builder.py#L674) which always returns `None`, so 

```not self._check_path(self.charm)```

will always be `True`.

### I expect/expected the following

Layers info to be printed

### What I got

An error: `build: For security reasons, only paths under your home directory can be accessed`

**Comment by battlemidget** [comment]
Can you try with edge snap? It uses classic confinement so this should not be an issue.

`sudo snap refresh charm --edge --classic`

**Comment by stnbu** [comment]
@battlemidget -- looks like it still happens on edge:

```
user@server:~$ snap info charm
name:      charm
summary:   charm and charm-tools
publisher: Cory Johns (johnsca)
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     edge
refresh-date: today at 14:10 PDT
channels:
  stable:    2.2.5                (176) 42MB -
  candidate: 2.2.5                (176) 42MB -
  beta:      2.3.1                (212) 46MB -
  edge:      2.3.1+git-5-g04ca207 (233) 47MB classic
installed:   2.3.1+git-5-g04ca207 (233) 47MB classic
user@server:~$ charm layers ./mycharm
build: For security reasons, only paths under your home directory can be accessed
```

Is there something more that I need to do?

**Comment by stnbu** [comment]
> Can you try with edge snap? It uses classic confinement so this should not be an issue.
> 
> `sudo snap refresh charm --edge --classic`

Ah. I misunderstood your point. This is new territory for me. Your suggestion should work. Thanks.

**Comment by johnsca** [comment]
I think the check actually needs to be removed from the code in edge.  This will have to be done prior to promoting edge.
