### ISSUE TITLE
charm-tools pypi package shows "unknown" version and has virtualenv build errors

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charm-tools#457]
Reproducer:

```
virtualenv venv
. venv/bin/activate
pip install charm-tools
pip freeze
```

**Comment by ryan-beisner** [comment]
```
(venv) rbeisner@rby:~/git$ pip freeze | grep charm-tools
charm-tools===unknown
```

**Comment by ryan-beisner** [comment]
This is causing virtualenv build failures at the current pypi release.

**Comment by johnsca** [comment]
This is due to pip calling `setup.py` during install and it trying to get the version info from git again rather than using the cached `VERSION`.  Working on a fix.
