### ISSUE TITLE
Newly-created/-built charms do not respond to config-changed

### ISSUE THREAD

**Issue by paulgear** [juju/charm-tools#463]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `snap info charm` and got the following ouput:

```$ snap info charm
name:      charm
summary:   charm and charm-tools
publisher: Cory Johns (johnsca)
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     stable
refresh-date: 10 days ago, at 10:25 AEST
channels:                                    
  stable:    2.4.4                (254) 47MB classic
  candidate: 2.4.4                (254) 47MB classic
  beta:      2.4.4                (254) 47MB classic
  edge:      2.4.4+git-2-g1b1a32b (264) 46MB classic
installed:   2.3.1                (212) 46MB -
```

I am using: Ubuntu 18.04

### I expect/expected the following

Reactive charms should react when a configuration item changed.

### What I got

Newly created/built charms are unresponsive to config changes.  Making hook.template executable and adding a symlink to it from update-status and/or config-changed fixes this.

https://code.launchpad.net/~canonical-sysadmins/canonical-is-charms/+git/apt-stresstest/+ref/master (private charm) has an example of apparently-correct config.changed hook which does not execute unless these hooks are in place.

**Comment by paulgear** [comment]
It appears that this is due to building with an out-of-date toolset, and the fact that it was non-obvious that the package had become outdated.  In fact, I had multiple versions of old tools getting in the way, including .deb versions of charm & charm-tools from 16.04 and 17.10 PPAs, as well as the above-noted non-classic snap.

Is there a way we could get the snap to be a little more proactive in warning users that they need to upgrade, along with some tips about how?

**Comment by paulgear** [comment]
Asking people to run `charm version` as part of submitting an issue might also be helpful in this regard.

**Comment by jacekn** [comment]
I've just hit this bug using the "charm" package from the juju ppa:

```
$ apt-cache policy charm
charm:
  Installed: 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2
  Candidate: 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2
  Version table:
 *** 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2 500
        500 http://ppa.launchpad.net/juju/stable/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2.1.1-0ubuntu1 500
        500 http://gb.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

$ charm version
charm 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2
charm-tools 2.2.3
```

Xenial is still supported and the ppa seems to be in use. Could we get it fixed please?
