### ISSUE TITLE
$HOME is needed for juju-test with LXD provider

### ISSUE THREAD

**Issue by jrwren** [juju/charm-tools#47]
Removing the HOME env var, the $HOME/.config dir becomes /.config and lxd-provider cannot locate lxd.

Workaround: run juju-test with -p HOME

Expected behavior: workaround should be unnecessary.

**Comment by marcoceppi** [comment]
It's great that you're using `juju test`, but `bundletester` is the way we're recommending testing going forward with the goal of folding that into charm-tools.

Does `bundletester` work for you? I'm willing to make the patch that `$HOME` is automagically forwarded in but I'd like to make sure bundletester works for you.
