### ISSUE TITLE
`charm build` uses cached layer repos without updating them

### ISSUE THREAD

**Issue by Cynerva** [juju/charm-tools#487]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `snap info charm` and got the following ouput:

```
name:      charm
summary:   charm and charm-tools
publisher: Cory Johns (johnsca)
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     stable
refresh-date: today at 10:17 CST
channels:
  stable:    2.5.2                2019-02-07 (320) 47MB classic
  candidate: 2.5.2                2019-02-07 (320) 47MB classic
  beta:      2.5.2                2019-02-07 (320) 47MB classic
  edge:      2.5.2+git-3-gef3d9a6 2019-02-12 (326) 47MB classic
installed:   2.5.2                           (320) 47MB classic
```

This issue occurs on 2.5.2+git-3-gef3d9a6 as well.

I am using: Ubuntu 16.04

### I expect/expected the following

I ran `charm build --no-local-layers` on the kubernetes-worker charm, and expected to have the changes from https://github.com/juju-solutions/layer-docker/commit/bcbd7e61ce3c747163b3a91fbc2f61f92ddff005 (which is in master) in the built charm.

### What I got

The built charm did not include the changes.

The `.build.manifest` confirms that the files were pulled from the correct layer, but an older git revision:
```
...
{
  "rev": "91a4a494c4250ac0c6b96f2622f6428d0b5556f7",
  "url": "layer:docker"
},
...
"templates/docker.defaults": [
  "layer:docker",
  "static",
  "eca57b5c847948cd1f9bc4e8968f24c114ebf005729d873a89684d047844f33c"
],
...
```

After this, I did `rm -rf ~/.cache/charm` and ran `charm build --no-local-layers` again. This time, the newly built charm had the correct git revision and the changes I expected.

**Comment by johnsca** [comment]
The code that manages this is in [charmtools/build/builder.py in `fetch_dep` (lines 288-316)](https://github.com/juju/charm-tools/blob/master/charmtools/build/builder.py#L288-L316)
