### ISSUE TITLE
charm does not error when missing series in metadata.yaml

### ISSUE THREAD

**Issue by johnsca** [juju/charm-tools#497]
[originally reported](https://github.com/juju-solutions/charms.reactive/issues/207) by @mitechie 
> charm proof (and build when checking proof) should throw an error when series is not specified in metadata.yaml. It should be a valid list of one or more series.

**Comment by johnsca** [comment]
@mitechie This isn't technically true, for historical reasons, but it sounds like we want to block that going forward?  I'm +1 to that.

**Comment by mitechie** [comment]
Right, this is a bug report suggesting we've had the feature and it's trivial enough to support for charmers that we begin enforcing it as required data. Apologies for the confusion.
