### ISSUE TITLE
Successful charm build returns error code 100

### ISSUE THREAD

**Issue by AdamIsrael** [juju/charm-tools#511]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [x] Provide versions of tools used
 - [x] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `snap info charm` and got the following ouput:

```
name:      charm
summary:   charm and charm-tools
publisher: Cory Johns (johnsca)
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     stable
refresh-date: 36 days ago, at 23:09 EST
channels:
  stable:    2.5.2                2019-02-07 (320) 47MB classic
  candidate: 2.5.2                2019-02-07 (320) 47MB classic
  beta:      2.5.2                2019-02-07 (320) 47MB classic
  edge:      2.5.2+git-15-28f7182 2019-03-11 (328) 57MB classic
installed:   2.5.2                           (320) 47MB classic
```

I am using: Ubuntu 18.04.2

### I expect/expected the following

I run `charm build` as part of integration testing. I discovered that the command is now returning the error code 100 despite finishing successfully.

```
charm build --no-local-layers /home/stone/src/osm/n2vc-564/tests/charms/layers/metrics-ci -o /home/stone/src/osm/n2vc-564/tests/charms/
```
### What I got

```
$ charm build --no-local-layers /home/stone/src/osm/n2vc-564/tests/charms/layers/metrics-ci -o /home/stone/src/osm/n2vc-564/tests/charms/

build: DEPRECATED: INTERFACE_PATH environment variable; please use CHARM_INTERFACES_DIR instead
build: DEPRECATED: LAYER_PATH environment variable; please use CHARM_LAYERS_DIR instead
build: Please add a `repo` key to your layer.yaml, with a url from which your layer can be cloned.
build: Destination charm directory: /home/stone/src/osm/n2vc-564/tests/charms/builds/metrics-ci
build: Processing layer: layer:options
build: Processing layer: layer:basic
build: Processing layer: layer:metrics
build: Processing layer: metrics-ci (from ../../../../../../n2vc-564/tests/charms/layers/metrics-ci)
proof: I: `display-name` not provided, add for custom naming in the UI
proof: I: No icon.svg file.
proof: W: Includes template README.ex file
proof: W: README.ex includes boilerplate: Step by step instructions on using the charm:
proof: W: README.ex includes boilerplate: You can then browse to http://ip-address to configure the service.
proof: W: README.ex includes boilerplate: - Upstream mailing list or contact information
proof: W: README.ex includes boilerplate: - Feel free to add things if it's useful for users
proof: I: all charms should provide at least one thing
$ echo $?
100
```
I would expect that a successful run of `charm build` would return error code 0.

**Comment by ryan-beisner** [comment]
A charm build is expected to pass a `charm proof` against the built artifact.  The W (WARN) lines in the output indicate failure of the charm proof linter.  Admittedly, it is confusing that a WARN here actually acts like an ERROR, but it does.

**Comment by AdamIsrael** [comment]
That must be a fairly recent change in behavior? I'd been using these charms in testing in my last cycle (last November or so) and `charm build` wasn't returning the error code then.

I've already updated my test framework, but I wanted to raise the issue just in case it wasn't intended.

**Comment by johnsca** [comment]
@AdamIsrael You submitted [the PR](https://github.com/juju/charm-tools/pull/443) which made proof affect the exit code, and the exit code has been 100 for WARN and 200 for ERROR for [6 years](https://github.com/juju/charm-tools/blame/master/charmtools/linter.py).  There was an issue with the snap build for a while, so if you're using edge, the PR might have only just made its way in, even though it was merged a while back.

**Comment by AdamIsrael** [comment]
So I did! I've been using the snap exclusively, so that may be what changed then.

What I should have done with that PR is add it to the docs. I'll assign this issue to myself and propose a doc update to rectify shortly.

Thanks for entertaining my faulty memory!

**Comment by AdamIsrael** [comment]
Added some documentation to the [discourse page](https://discourse.jujucharms.com/t/debugging-building-layers/1115) for debugging and building layers.
