### ISSUE TITLE
'charm proof' thinks two character config setting is an error

### ISSUE THREAD

**Issue by stub42** [juju/charm-tools#533]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `snap info charm` and got the following ouput:

```
name:      charm
summary:   charm and charm-tools
publisher: Cory Johns (johnsca)
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     edge
refresh-date: 18 days ago, at 22:36 +07
channels:
  stable:    2.6.0 2019-06-06 (345) 57MB classic
  candidate: 2.6.0 2019-06-06 (345) 57MB classic
  beta:      2.6.0 2019-06-06 (345) 57MB classic
  edge:      2.6.0 2019-06-13 (347) 58MB classic
installed:   2.6.0            (347) 58MB classic
```

I am using: Ubuntu, snap

### I expect/expected the following

'charm proof' to report success on this charm, like it used to.

### What I got

'charm proof' reports an error, and returns a failure code:

```
proof: E: config.yaml: ca does not conform to naming pattern
```

I don't think it likes my two character config setting. Unfortunately, changing this to the more long winded certificate_authority would be backwards incompatible.

**Comment by stub42** [comment]
'charm build' fails too, because it runs proof after the build.

**Comment by johnsca** [comment]
It seems that this check goes back six years, so I'm not sure why you think it used to be allowed, unless maybe you just started hitting it when proof started being enforced during build a little while back?

I merged the PR, but now I'm having second thoughts on allowing such short config option names.  Especially just a single character..

**Comment by stub42** [comment]
It would have broken things when 'charm build' started doing proof, and failing if the proof saw an error. This is an internal charm, not rebuilt often.

I would be fine with short config options being a warning. I don't think they should be an error unless Juju agrees to treat them as an error (which it can't until a backwards incompatible release).
