### ISSUE TITLE
Building: -d and -o differ

### ISSUE THREAD

**Issue by sabaini** [juju/charm-tools#563]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?
I ran the following command: `snap info charm` and got the following ouput:
name:      charm
summary:   charm and charm-tools
publisher: Canonical✓
store-url: https://snapcraft.io/charm
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     latest/stable
refresh-date: 22 days ago, at 21:32 CET
channels:
  latest/stable:    2.7.4 2020-03-26 (461) 116MB classic
  latest/candidate: 2.7.4 2020-03-26 (461) 116MB classic
  latest/beta:      2.7.4 2020-03-26 (461) 116MB classic
  latest/edge:      2.7.4 2020-03-26 (461) 116MB classic
installed:          2.7.4            (461) 116MB classic

I am using: (Your operating system)

Ubuntu Eoan

## Issue/Feature

Per the documentation the -o and -d flags should be the same:
charm build -h
...
  -o OUTPUT_DIR, --output-dir OUTPUT_DIR
                        Alias for --build-dir

However, it's not really:

charm build . -d /tmp/x
build: Destination charm directory: /tmp/x/<myapp>
...
charm build . -o /tmp/x
build: Destination charm directory: /tmp/x/builds/<myapp>
...
### I expect/expected the following

With -d and -o built charm should end up in the same dir

### What I got

-o adds a builds/ dir to the given path, -d doesn't

**Comment by johnsca** [comment]
Fixed in #564
