### ISSUE TITLE
broken url in generated hook

### ISSUE THREAD

**Issue by kwmonroe** [juju/charm-tools#59]
This puts a broken link in my generated hooks:

https://github.com/juju/charm-tools/blob/master/charmtools/build/tactics.py#L217

The URL from the above line should probably point to here, no?

https://jujucharms.com/docs/stable/authors-charm-building

**Comment by marcoceppi** [comment]
Yes, since the docs have no clue how to properly redirect rewritten URLs
we're just constantly breaking them.

**Comment by kwmonroe** [comment]
fixed in #60 if you like

**Comment by kwmonroe** [comment]
closing since #60 was merged
