### ISSUE TITLE
PR 585 broke custom WheelhouseTactic overriding

### ISSUE THREAD

**Issue by johnsca** [juju/charm-tools#596]
[This explicit reference to the base `WheelhouseTactic`](https://github.com/juju/charm-tools/pull/585/files#diff-ed28d309f96602c0413266af4535f3106d2f02a41fdc6b354b1466693df3a5dcR409) from PR #585 broke the ability for layers (specifically [caas-base](https://github.com/juju-solutions/layer-caas-base/blob/master/tactics/wheelhouse.py)) to override the `WheelhouseTactic` because it doesn't honor override list.  Actually, both of the explicit uses of `WheelhouseTactic` in that function (i.e., also [this one](https://github.com/juju/charm-tools/blob/75272c7d014052efa191f3952ce45594f6fd5e04/charmtools/build/builder.py#L427)) should be fixed to get the type of the `existing_tactic` and only fall back to the base class if it doesn't exist.

**Comment by johnsca** [comment]
I've worked around this for now in https://github.com/juju-solutions/layer-caas-base/pull/28 and AFAIK that layer is the only one affected, but this should be fixed properly at some point.

**Comment by ajkavanagh** [comment]
This is probably fixed by #598; please could you verify?  Thanks.

**Comment by johnsca** [comment]
Fixed by #598
