### ISSUE TITLE
some openstack charms don't build with pip version of charm-tools

### ISSUE THREAD

**Issue by tbaumann** [juju/charm-tools#613]
## What version am I running?

I ran the following command: `charm-version` and got the following ouput:

```
# charm-version 
charmstore-client unavailable
charm-tools 2.8.3

```

I am using: Ubuntu, bionic, focal and impish

## Issue/Feature

On a freshly installed Ubuntu or in a bare venv I get this error when building some openstack charms.

https://pastebin.ubuntu.com/p/6Ss2Nvmj8R/

Some affected charms are 

https://opendev.org/openstack/charm-octavia.git stable/21.10 branch
https://git.launchpad.net/ntp-charm master branch

The error seems to be related to the command `pip install --no-binary :all:` in 'build/tactics.py'

If I remove that parameter it builds just fine.

There are some circumstances where it works. My somewhat old and cluttered impish workstation can build those charms.

But a fresh install doesn't.

Strangely, also working is the snap version of the charm tools. But I need to use the pip because I use it in a Docker container.

`pip install --verbose --no-binary :all: Tempita` straight on the system works by the way. Something about the way it's done in this tool makes it fail.

I don't know python enough to be able to tell if `--no-binary :all:` makes sense and if removing it is the right fix. But that worked for us.

**Comment by tbaumann** [comment]
Canonical case 00328820

**Comment by tbaumann** [comment]
PS: The charm builds fine if I remove `--no-binary :all:` but the charms don't install.

**Comment by tbaumann** [comment]
Something weird happened. I can no longer reproduce the issue. (on a fresh focal container)
I think it must have been one of the pip dependencies, because charm-version is still charm-tools 2.8.3 and the charm hasn't changed.
I don't know what to think of this. I guess we can consider it fixed. I was totally able to reproduce this reliably and cleanly. Not it's gone.

**Comment by ajkavanagh** [comment]
We recently made [some changes](https://github.com/juju-solutions/layer-basic/pull/199) to layer-basic to cope with building on jammy.  This is the error from in your build:

```
Collecting Tempita
  Using cached Tempita-0.5.2.tar.gz (12 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in Tempita setup command: use_2to3 is invalid.
      [end of output]
```

The `use_2to3` is the key piece of information; it's been removed from [setuptools >= 58.0](https://setuptools.pypa.io/en/latest/history.html#v58-0-0).  You could pin setuptools, but then you run into other issues with py310.

So now, layer-basic is 'aware' of what it is building on.  If it is pre python 3.8, then you get one set of pins that works for py35-py37, otherwise you get a charm that will work on py38 forwards.

Also, charmhelpers [recently](https://discourse.charmhub.io/t/removing-py27-p35-from-charm-helpers-library/5335) had some changes which essentially means that:

 * <1.0.0 py27+
 * <2.0.0 py35+

It's probably useful/necessary to pin to < 2.0.0 rather than 1.0.0 if you are including charmhelpers.

This probably deserves a chamhub discourse post.

**Comment by tbaumann** [comment]
Huh, no it's not true. 

I tested the aodh charm (just as a random example. The wheelhouse.txt of version stable/21.10 points to `git+https://github.com/juju/charm-helpers.git@stable/21.10#egg=charmhelpers`
That version does not have that breaking change yet.

The charm source is unmodified and build on focal.
It installs on focal but not bionic.

Bionic log
```
unit-aodh-0: 16:01:45 WARNING unit.aodh/0.install Command "/var/lib/juju/agents/unit-aodh-0/.venv/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-fyrdz0t8 --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links wheelhouse --" failed with error code 1 in None
unit-aodh-0: 16:01:45 WARNING unit.aodh/0.install Traceback (most recent call last):
unit-aodh-0: 16:01:45 WARNING unit.aodh/0.install   File "/var/lib/juju/agents/unit-aodh-0/charm/hooks/install", line 8, in <module>
unit-aodh-0: 16:01:45 WARNING unit.aodh/0.install     basic.bootstrap_charm_deps()
unit-aodh-0: 16:01:45 WARNING unit.aodh/0.install   File "lib/charms/layer/basic.py", line 221, in bootstrap_charm_deps
unit-aodh-0: 16:01:45 WARNING unit.aodh/0.install     env=_get_subprocess_env())
unit-aodh-0: 16:01:45 WARNING unit.aodh/0.install   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
unit-aodh-0: 16:01:45 WARNING unit.aodh/0.install     raise CalledProcessError(retcode, cmd)
unit-aodh-0: 16:01:45 WARNING unit.aodh/0.install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-aodh-0/.venv/bin/pip', 'install', '-U', '--force-reinstall', '--no-index', '--no-cache-dir', '-f', 'wheelhouse', 'charmhelpers==0.20.24.dev2', 'PyYAML==5.2', 'netaddr==0.7.19', 'dnspython==1.16.0', 'Tempita==0.4', 'flit-core==3.7.1', 'Jinja2==2.10.1', 'charms.reactive==1.4.1', 'netifaces==0.11.0', 'pbr==5.6.0', 'psutil==5.8.0', 'charms.openstack==0.0.1.dev1', 'pyaml==21.10.1', 'six==1.16.0']' returned non-zero exit status 1.
unit-aodh-0: 16:01:45 ERROR juju.worker.uniter.operation hook "install" (via explicit, bespoke hook script) failed: exit status 1
unit-aodh-0: 16:01:45 INFO juju.worker.uniter awaiting error resolution for "install" hook
```

I am getting a bit crazy over this TBH. :laughing:

**Comment by tbaumann** [comment]
May I ask, how do you build charms for official release? Is there perhaps a release process we can copy?

We kept it simple. Just a docker with charm-tools installed in a venv...

PS: I see you are going towards charmcraft. Potentially nice. But lxc inside docker is even more of a pain...

**Comment by ajkavanagh** [comment]
@tbaumann ah, stable charms are a different story as we use the build lock-file feature of charm-tools.  Thus the stable/21.10 charms use a set of layers (locked to specific commits) and modules (locked to specific versions) to try to exactly reproduce the charm in its stable form.  If you have a look at the tox.ini for (say) the aodh charm, you'll see that the `build-reactive` target has an extra param:

```
[testenv:build-reactive]
basepython = python3
commands =
    charm-build --log-level DEBUG --use-lock-file-branches -o {toxinidir}/build/builds src {posargs}
```

(Note that we have `build` and `build-reactive` as we are now using charmcraft to build the charm in launchpad and thus have to have two steps ... this gets complicated fast!)

Anyway, that means that the stable charms use a version of layer-basic that predates the change that introduced the py310 support and thus all that extra pinning.

So for stable/21.10 we *actually* built all our charms on Xenial and ran them on Xenial, Bionic and Focal ... it's just that a Xenial built charm (i.e. with modules that work on py35) simply couldn't be made to work on py310 on Jammy.  Neither could we get the bionic built ones to work on py310.

So our actual strategy going forwards is to have charms in charmhub that support two LTS releases.  e.g. the focal (base 20.04) will also support bionic (base 18.04) and be *built* on bionic as that will also run on focal.  This is for series upgrade support.  And the jammy charm will work on focal, and be built on focal, as the py38 modules *do* work on py310.

We dropped Xenial support this cycle, but still need to support bionic going forwards.  However, our next charm release only needs to support focal and jammy.  We're re-engineering our stable/21.10 charms into a set of tracks to support back to bionic.

Our release process is something like this at the moment.

* We now build our charms in Launchpad using the LP charm recipe feature.
* Thus charms have to be built by charmcraft.  This does mean an LXC build.  We build a charm for a track that supports the targeted LTS and the previous one, and build it on the previous one for compatibility.
* We have the charms automatically pushed to <track>/edge.
* We'll manually promote them to <track>/stable at the appropriate time.
* We're not entirely sure what to do with latest/stable!

Currently, latest/stable maps to our last stable charms release (git branch=stable/21.10) and we're not planning on changing that for the next release.  Our next release of charms will be to the yoga/stable (for openstack charms), quincy/stable (for ceph charms), etc.  We're leaving latest/stable for the 21.10 charms as that makes sense for our installed base.

We're still working out tooling for the final release process!

I hope this makes some sense?  If not, please keep asking questions :)

**Comment by tbaumann** [comment]
So it seems obvious to me that the answer is to Build the charms on Bionic at the moment.
I tried it on a Bionic lxc container. It worked fine.
But the same thing on Docker fails. The steps I took are the same (see Dockerfile below)

Straight up Docker based on 
```Dockerfile
FROM ubuntu:18.04


ENV DEBIAN_FRONTEND=noninteractive


RUN apt update
RUN apt-get install --yes \
    python3-pip python3-dev python3-venv git wget

## venv
RUN python3 -m venv /opt/charm_venv
RUN . /opt/charm_venv/bin/activate && \
    pip install charm-tools tox "cryptography<3.4" wheel

## Install jfrog cli to be able to upload to artifactory
RUN wget -qO - https://releases.jfrog.io/artifactory/api/gpg/key/public | \
    apt-key add -; \
    echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | \
    tee -a /etc/apt/sources.list; \
    apt update; \
    apt install -y jfrog-cli
```

Trying to build ntp layer (others are the same)
https://pastebin.ubuntu.com/p/hfQxVK9c4x/
UnicodeEncodeError: 'ascii' codec can't encode characters in position 105-107: ordinal not in range(128)

The whole thing happens again in the venv that the build tools set up. So I have little way of influencing that behavior.
I tried `PYTHONIOENCODING=utf8 charm-build ...` but makes no difference.
Surprisingly it's a py3.6 venv. Not what I expected TBH.

**Comment by tbaumann** [comment]
```Dockerfile
 ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
```
:facepalm: yea nevermind about my last comment.

**Comment by tbaumann** [comment]
Charms built on bionic work on bionic. All good.

While I have your attention. Is it possible to use charmcraft to generate artifacts for multiple series?

**Comment by tbaumann** [comment]
I mean multiple variations of `bases:` so far my experiments failed. I always only get one build-on and run-on to work.
I would have thought it should be possible to create various combinations in one pack command.

**Comment by ajkavanagh** [comment]
> I mean multiple variations of `bases:` so far my experiments failed. I always only get one build-on and run-on to work. I would have thought it should be possible to create various combinations in one pack command.

So charmcraft will only build one base at a time.  The `charmcraft pack` command has a `--bases-index` param that let's you select a different base to build on.  Like all good programming indexes, it's 0-indexed, not 1-indexed!

We decided that since reactive charms tend to be "all" architectures (as the pip modules are installed from wheels at install time, and any binary build requirements can be installed then), that we would build on amd64 but run on the 4 arches we are interested in.  Thus our focal charms (that will also run on jammy) are specified as:

```yaml
bases:
  - build-on:
      - name: ubuntu
        channel: "20.04"
        architectures:
          - amd64
    run-on:
      - name: ubuntu
        channel: "20.04"
        architectures: [amd64, s390x, ppc64el, arm64]
      - name: ubuntu
        channel: "22.04"
        architectures: [amd64, s390x, ppc64el, arm64]
```

i.e. build on 20.04 (focal) and run on 20.04 and 22.04 on the 4 arches.  It may even be possible to specify "all" as an arch, although I haven't tried it!  Note that there is only one base there, as `build-on` and `run-on` are keys in the first (and only) list under `bases`.

**Comment by tbaumann** [comment]
Thank you for the explanation. That's useful.

Closing the case. Thanks for your help.
