### ISSUE TITLE
validate_series should not raise an error if series is missing

### ISSUE THREAD

**Issue by r-f-g** [juju/charm-tools#615]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [x] Provide versions of tools used
 - [x] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `snap info charm` and got the following ouput:

```
$ snap info charm
name:      charm
summary:   charm and charm-tools
publisher: Canonical✓
store-url: https://snapcraft.io/charm
contact:   https://discourse.juju.is/c/charming
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     latest/stable
refresh-date: today at 11:43 CEST
channels:
  latest/stable:    2.8.2               2021-02-01 (609) 119MB classic
  latest/candidate: 2.8.2               2021-02-01 (609) 119MB classic
  latest/beta:      2.8.2               2021-02-01 (609) 119MB classic
  latest/edge:      2.8.3+git-1-736b1ad 2021-02-23 (620) 119MB classic
installed:          2.8.2                          (609) 119MB classic    
```

I am using: 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy   
```

I also tried using the version installed with pip directly from the master branch ([commit](https://github.com/juju/charm-tools/tree/6f21011580ebf0b4fe7728edcd5010de84baa4b2)).

## Issue/Feature

When I remove `series` from `metadata.yaml`, `charm build` does not work because of these [lines](https://github.com/juju/charm-tools/blob/736b1ade28882290976f4703346d5edc866502c8/charmtools/charms.py#L822-L823). 

In my case, I tried to remove the series from [charm-telegraf](https://git.launchpad.net/charm-telegraf/tree/src/metadata.yaml), which did not work. However, for most reactive openstack charms this will work fine thanks to `layer:openstack-api` which is defined with `series: []`.

### I expect/expected the following

```
$ charm build
...
build: 
build: ---------------------------------------
build:               Build Report
build: ---------------------------------------
build:    metadata.yaml
```

### What I got

```
$ charm build
...
proof: E: missing series: must be a list of series names  
```

**Comment by ajkavanagh** [comment]
`series` used to be a required field in the `metadata.yaml` and so charm-tools validated that it existed.  It's now optional (and I think ignored by charmcraft, which uses the `bases` parameter from the `charmcraft.yaml`).  I also think it will be removed entirely shortly.  Obviously, only charmcraft is capable of uploading to charmhub, so `series` is now unneeded.

I think we should remove the check, or reverse it and indicate that the key is no longer needed as an info point during `charm build`.

**Comment by r-f-g** [comment]
Hi Alex, I was confused by your answer and then I realized that I made a mistake. My intention was to use `if 'series' in charm:` and that way the function will only display a warning message when `series` is there. So I agree with what you and I'm going to propose a PR with this change.
