### ISSUE TITLE
No control over virtualenv used to build wheels

### ISSUE THREAD

**Issue by fnordahl** [juju/charm-tools#646]
Some python packages may require changes to the virtualenv used to build wheels. There is currently no way of doing that.

One example is Jinja2 when building on Focal (ref pallets/jinja#1496):
https://github.com/juju/charm-tools/blob/977ec1ff795f5a8692f8061fc16aa01adf9478cf/.github/workflows/tests.yml#L57-L66

The virtualenv is created by charm-tools here:
https://github.com/juju/charm-tools/blob/977ec1ff795f5a8692f8061fc16aa01adf9478cf/charmtools/build/tactics.py#L1241-L1244

**Comment by facundobatista** [comment]
+1 to this issue.

When `charmcraft` packs a charm using the `charm` plugin, it builds a virtualenv and then allows the user to install packages there before actually dealing the charm requirements. This way, the user can upgrade `setuptools` and `pip`, a step that is needed for later proper installation of Jinja2 (the Focal default versions of `setuptools` and `pip` do not handle that correctly).

But in the case of `charmcraft` packing a charm using the `reactive` plugin, it will end up calling `charm`, which is the one responsible of the virtualenv creation and installation of charm requirements. As everything is handled in the same `charm` tool process, there is no way `charmcraft` can get in the middle and update these packages "from outside".

So it would be awesome if the `charm` tool handleds this. Thank you!!

**Comment by hloeung** [comment]
+1 here too. With charm tools 2.x, we can override python packages in `wheelhouse.txt`. This breaks with 3.x (at least with `3.0.4`).

Downgrading to `2.x/stable` either in charmcraft.yaml with `build-snaps: [charm/2.x/stable]` as mentioned in https://github.com/juju-solutions/layer-basic/issues/209 fixes this for me.

**Comment by lathiat** [comment]
Does this change fix this:
https://discourse.charmhub.io/t/install-or-update-python-packages-before-packing-a-charm/5158

See also: https://github.com/canonical/charmcraft/issues/551

**Comment by fnordahl** [comment]
> Does this change fix this: https://discourse.charmhub.io/t/install-or-update-python-packages-before-packing-a-charm/5158
> 
> See also: [canonical/charmcraft#551](https://github.com/canonical/charmcraft/issues/551)

No, when building with the reactive plugin, charm-tools is in charge of the virtualenv, the fix in charmcraft only affects building with the charm plugin for operator framework charms. See also https://github.com/juju/charm-tools/issues/646#issuecomment-1273451182
