### ISSUE TITLE
Generated relation and storage hooks are broken in 1.10

### ISSUE THREAD

**Issue by axw** [juju/charm-tools#69]
I've just built a reactive charm with 1.10, and had errors in storage-attached due to the generated hook file having a blank line before the shebang. Probably broken with the change over to using Python 3.

**Comment by cmars** [comment]
I can confirm, my layered charms are affected. All the relation hooks seem to have the extra line before the shebang.

**Comment by gnuoy** [comment]
Me too. Blank line at top of generated hook file and python3 seems to fail to import charms.reactive:

# ./hooks/database-relation-changed
./hooks/database-relation-changed: line 5: import: command not found
./hooks/database-relation-changed: line 6: syntax error near unexpected token `'lib''
./hooks/database-relation-changed: line 6: `sys.path.append('lib')'
# sed -i -e "1d" ./hooks/database-relation-changed
# ./hooks/database-relation-changed
Traceback (most recent call last):
  File "./hooks/database-relation-changed", line 13, in <module>
    from charms.reactive import main
ImportError: No module named 'charms'
# sed -i -e 's/python3/python/' ./hooks/database-relation-changed
# ./hooks/database-relation-changed
#

**Comment by cmars** [comment]
Thanks for this. When will this fix be available in ppa:juju/stable?

**Comment by johnsca** [comment]
For reference, @gnuoy's import issue after fixing the leading newline was due to juju-solutions/reactive-base-layer#10 not having been merged, which has since been resolved.
