### ISSUE TITLE
`charm create` should output a reactive charm

### ISSUE THREAD

**Issue by cmars** [juju/charm-tools#77]
When starting a new charm with `charm create`, the output should be a reactive charm. While it's certainly not hard to write a reactive charm from scratch (because it's so easy to write a reactive charm now!), I think it's important to update this, as it's possibly the first thing a learning charmer will try.

**Comment by marcoceppi** [comment]
I completely agree! We've talked about this a bit on and off. Thanks for
creating an issue to track it though!

**Comment by johnsca** [comment]
+1

**Comment by marcoceppi** [comment]
fixed in #113
