### ISSUE TITLE
Generate hook stubs for Windows

### ISSUE THREAD

**Issue by stub42** [juju/charm-tools#79]
We probably need to generate .cmd files for every hook to invoke the actual Python hook correctly.

**Comment by marcoceppi** [comment]
Would this be better served by having a Windows base layer which properly set up the hooks as .ps files which tapped into the reactive framework?

**Comment by stub42** [comment]
A Windows base layer would work for the main hooks, but not hooks installed by other layers or interfaces.

I think this is another facet of #98, where up to date hooks relevant for the supported series get generated from layer.yaml rather than potentially old versions get embedded in the source layers and interfaces.
