### ISSUE TITLE
charm proof does not properly lint 'actions.yaml'

### ISSUE THREAD

**Issue by chuckbutler** [juju/charm-tools#91]
When defining actions, there are a few key things to keep in mind and our current tooling does not check the action signatures for compliance of this format.

#### from the tooling developer documentation:

> Note: action names must start and end with lowercase alphanumeric characters, and only contain lowercase alphanumeric characters, the hyphen "-" or full stop"." characters.

cited: https://jujucharms.com/docs/devel/developer-actions

**Comment by johnsca** [comment]
Any idea why underscores are not in that list?

**Comment by chuckbutler** [comment]
No idea unfortunately. Its a usability paper cut imho
