### ISSUE TITLE
Layers can only use https: urls

### ISSUE THREAD

**Issue by stub42** [juju/charm-tools#96]
Per https://bugs.launchpad.net/leadership-layer/+bug/1539142 , charm-build doesn't know how to handle layers resolving to git: or git+ssh: urls. https: seems to be the only option.

**Comment by johnsca** [comment]
It looks like it should handle git:// URLs but not git+ssh:// URLs: https://github.com/juju/charm-tools/blob/master/charmtools/fetchers.py#L120

That seems to make sense to me, since it wouldn't have ssh config to use.  I have not tested this.

**Comment by stub42** [comment]
Its failing with git: too:

charmtools.fetchers.FetchError: No fetcher for url: git://git.launchpad.net/layer-coordinator
